services:
  chatserver:
    build:
      context: .
      dockerfile: server/chat/Dockerfile
    volumes:
      - ./logs/chatserver:/logs
    ports:
      - "50051:50051"
    networks:
      - spelltext
    develop:
      watch:
        - action: "restart"
          path: "./server/chat" 
    depends_on:
      - nats
  
  storeserver:
    build:
      context: .
      dockerfile: server/store/Dockerfile
    volumes:
      - ./logs/storeserver:/logs
    ports:
      - "50052:50052"
    networks:
      - spelltext
    develop:
      watch:
        - action: "restart"
          path: "./server/store"
    depends_on:
      - postgres
      
  inventoryserver:
    build:
      context: .
      dockerfile: server/inventory/Dockerfile
    volumes:
      - ./logs/inventoryserver:/logs
    ports:
      - "50053:50053"
    networks:
      - spelltext
    develop:
      watch:
        - action: "restart"
          path: "./server/inventory"
    depends_on:
      - postgres
  
  nats:
    image: nats
    command: ["-js"]
    ports:
      - "4222:4222"
    networks:
      - spelltext  
    
  flyway:
    build:
      context: scripts/db
      dockerfile: Dockerfile
    volumes:
      - ./scripts/db/sql:/flyway/sql
    networks:
      - spelltext
    command: ["-url=jdbc:postgresql://postgres:5432/spelltext", "-user=user", "-password=changeme"  ,"-baselineOnMigrate=true", "-connectRetries=15",  "migrate"]
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=user
      - POSTGRES_DB=spelltext
      - POSTGRES_REQUIRE_AUTH=false
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - spelltext
    restart: always
  
  pgadmin:
    container_name: core-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: test@mail.com
      PGADMIN_DEFAULT_PASSWORD: changeme
    networks:
      - spelltext
    ports:
      - "5434:80"
    
  
networks:
  spelltext: