chatserver:
  port: 50051
  natsUrl: nats://spelltext-nats:4222
  maxAsyncPublish: 512

storeserver:
  port: 50052
  pgUser: storeuser
  pgPass: changeme
  # pgHost: spelltext-postgresql-ha-pgpool.spelltext.svc.cluster.local
  pgHost: postgres
  pgPort: 5432
  pgDbName: spelltext
  pgSslMode: disable

inventoryserver:
  port: 50053
  pgUser: inventoryuser
  pgPass: changeme
  # pgHost: spelltext-postgresql-ha-pgpool.spelltext.svc.cluster.local
  pgHost: postgres
  pgPort: 5432
  pgDbName: spelltext
  pgSslMode: disable

charserver:
  port: 50054
  pgUser: charuser
  pgPass: changeme
  # pgHost: spelltext-postgresql-ha-pgpool.spelltext.svc.cluster.local
  pgHost: postgres
  pgPort: 5432
  pgDbName: spelltext
  pgSslMode: disable

gambaserver:
  port: 50055
  pgUser: gambauser
  pgPass: changeme
  # pgHost: spelltext-postgresql-ha-pgpool.spelltext.svc.cluster.local
  pgHost: postgres
  pgPort: 5432
  pgDbName: spelltext
  pgSslMode: disable

authserver:
  port: 50056
  pgUser: storeuser
  pgPass: changeme
  # pgHost: spelltext-postgresql-ha-pgpool.spelltext.svc.cluster.local
  pgHost: postgres
  pgPort: 5432
  pgDbName: spelltext
  pgSslMode: disable
  authType: hash
  trust: true

  charserver:
    port: 50054