postgres:
  # host: spelltext-postgresql-ha-pgpool.spelltext.svc.cluster.local
  host: postgres
  port: 5432

chatserver:
  port: 50051
  natsUrl: nats://spelltext-nats:4222
  maxAsyncPublish: 512

storeserver:
  port: 50052
  pgUser: storeuser
  pgPass: changeme
  pgDbName: spelltext
  pgSslMode: disable

inventoryserver:
  port: 50053
  pgUser: inventoryuser
  pgPass: changeme
  pgDbName: spelltext
  pgSslMode: disable

charserver:
  port: 50054
  pgUser: charuser
  pgPass: changeme
  pgDbName: spelltext
  pgSslMode: disable

gambaserver:
  port: 50055
  pgUser: gambauser
  pgPass: changeme
  pgDbName: spelltext
  pgSslMode: disable

authserver:
  port: 50056
  pgUser: authuser
  pgPass: changeme
  pgDbName: spelltext
  pgSslMode: disable
  authType: hash
  trust: true

  healthCheckInterval: 5
  maxReconnectAttempts: 2
  backoff: 2

combatserver:
  port: 50057
  pgUser: combatuser
  pgPass: changeme
  pgDbName: spelltext
  pgSslMode: disable

buildserver:
  port: 50058
  pgUser: builduser
  pgPass: changeme
  pgDbName: spelltext
  pgSslMode: disable

  healthCheckInterval: 5
  maxReconnectAttempts: 2
  backoff: 2
