// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: store.proto

package store

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreListVendorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Noop          string                 `protobuf:"bytes,1,opt,name=noop,proto3" json:"noop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreListVendorRequest) Reset() {
	*x = StoreListVendorRequest{}
	mi := &file_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreListVendorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreListVendorRequest) ProtoMessage() {}

func (x *StoreListVendorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreListVendorRequest.ProtoReflect.Descriptor instead.
func (*StoreListVendorRequest) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{0}
}

func (x *StoreListVendorRequest) GetNoop() string {
	if x != nil {
		return x.Noop
	}
	return ""
}

type Vendor struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	VendorId              uint64                 `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	VendorName            string                 `protobuf:"bytes,2,opt,name=vendor_name,json=vendorName,proto3" json:"vendor_name,omitempty"`
	VendorWareDescription string                 `protobuf:"bytes,3,opt,name=vendor_ware_description,json=vendorWareDescription,proto3" json:"vendor_ware_description,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Vendor) Reset() {
	*x = Vendor{}
	mi := &file_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vendor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vendor) ProtoMessage() {}

func (x *Vendor) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vendor.ProtoReflect.Descriptor instead.
func (*Vendor) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{1}
}

func (x *Vendor) GetVendorId() uint64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *Vendor) GetVendorName() string {
	if x != nil {
		return x.VendorName
	}
	return ""
}

func (x *Vendor) GetVendorWareDescription() string {
	if x != nil {
		return x.VendorWareDescription
	}
	return ""
}

type StoreListVendorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendors       []*Vendor              `protobuf:"bytes,1,rep,name=vendors,proto3" json:"vendors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreListVendorResponse) Reset() {
	*x = StoreListVendorResponse{}
	mi := &file_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreListVendorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreListVendorResponse) ProtoMessage() {}

func (x *StoreListVendorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreListVendorResponse.ProtoReflect.Descriptor instead.
func (*StoreListVendorResponse) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{2}
}

func (x *StoreListVendorResponse) GetVendors() []*Vendor {
	if x != nil {
		return x.Vendors
	}
	return nil
}

type StoreListVendorItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VendorId      uint64                 `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"` // 0 = any
	RarityMin     int32                  `protobuf:"varint,2,opt,name=rarity_min,json=rarityMin,proto3" json:"rarity_min,omitempty"`
	RarityMax     int32                  `protobuf:"varint,3,opt,name=rarity_max,json=rarityMax,proto3" json:"rarity_max,omitempty"`
	Stackable     uint32                 `protobuf:"varint,4,opt,name=stackable,proto3" json:"stackable,omitempty"`
	InStock       uint32                 `protobuf:"varint,5,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	PageSize      int32                  `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	SortBy        string                 `protobuf:"bytes,12,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"` // "name", "rarity", "stock"
	SortDesc      bool                   `protobuf:"varint,13,opt,name=sort_desc,json=sortDesc,proto3" json:"sort_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreListVendorItemRequest) Reset() {
	*x = StoreListVendorItemRequest{}
	mi := &file_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreListVendorItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreListVendorItemRequest) ProtoMessage() {}

func (x *StoreListVendorItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreListVendorItemRequest.ProtoReflect.Descriptor instead.
func (*StoreListVendorItemRequest) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{3}
}

func (x *StoreListVendorItemRequest) GetVendorId() uint64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *StoreListVendorItemRequest) GetRarityMin() int32 {
	if x != nil {
		return x.RarityMin
	}
	return 0
}

func (x *StoreListVendorItemRequest) GetRarityMax() int32 {
	if x != nil {
		return x.RarityMax
	}
	return 0
}

func (x *StoreListVendorItemRequest) GetStackable() uint32 {
	if x != nil {
		return x.Stackable
	}
	return 0
}

func (x *StoreListVendorItemRequest) GetInStock() uint32 {
	if x != nil {
		return x.InStock
	}
	return 0
}

func (x *StoreListVendorItemRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *StoreListVendorItemRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *StoreListVendorItemRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *StoreListVendorItemRequest) GetSortDesc() bool {
	if x != nil {
		return x.SortDesc
	}
	return false
}

type ListVendorItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVendorItemResponse) Reset() {
	*x = ListVendorItemResponse{}
	mi := &file_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVendorItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVendorItemResponse) ProtoMessage() {}

func (x *ListVendorItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVendorItemResponse.ProtoReflect.Descriptor instead.
func (*ListVendorItemResponse) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{4}
}

func (x *ListVendorItemResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListVendorItemResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Item struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ItemTypeId       uint32                 `protobuf:"varint,3,opt,name=item_type_id,json=itemTypeId,proto3" json:"item_type_id,omitempty"`
	Rarity           uint32                 `protobuf:"varint,4,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Stackable        uint32                 `protobuf:"varint,5,opt,name=stackable,proto3" json:"stackable,omitempty"`
	StackSize        uint32                 `protobuf:"varint,6,opt,name=stack_size,json=stackSize,proto3" json:"stack_size,omitempty"`
	BindOnPickup     uint32                 `protobuf:"varint,7,opt,name=bind_on_pickup,json=bindOnPickup,proto3" json:"bind_on_pickup,omitempty"`
	Description      string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Metadata         *structpb.Struct       `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	HealthPoints     uint64                 `protobuf:"varint,11,opt,name=health_points,json=healthPoints,proto3" json:"health_points,omitempty"`
	PowerPoints      uint64                 `protobuf:"varint,12,opt,name=power_points,json=powerPoints,proto3" json:"power_points,omitempty"`
	StrengthPoints   uint64                 `protobuf:"varint,13,opt,name=strength_points,json=strengthPoints,proto3" json:"strength_points,omitempty"`
	SpellpowerPoints uint64                 `protobuf:"varint,14,opt,name=spellpower_points,json=spellpowerPoints,proto3" json:"spellpower_points,omitempty"`
	// Types that are valid to be assigned to TypeDetails:
	//
	//	*Item_Consumable
	//	*Item_Armor
	//	*Item_Weapon
	//	*Item_Generic
	TypeDetails   isItem_TypeDetails `protobuf_oneof:"type_details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{5}
}

func (x *Item) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetItemTypeId() uint32 {
	if x != nil {
		return x.ItemTypeId
	}
	return 0
}

func (x *Item) GetRarity() uint32 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *Item) GetStackable() uint32 {
	if x != nil {
		return x.Stackable
	}
	return 0
}

func (x *Item) GetStackSize() uint32 {
	if x != nil {
		return x.StackSize
	}
	return 0
}

func (x *Item) GetBindOnPickup() uint32 {
	if x != nil {
		return x.BindOnPickup
	}
	return 0
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Item) GetHealthPoints() uint64 {
	if x != nil {
		return x.HealthPoints
	}
	return 0
}

func (x *Item) GetPowerPoints() uint64 {
	if x != nil {
		return x.PowerPoints
	}
	return 0
}

func (x *Item) GetStrengthPoints() uint64 {
	if x != nil {
		return x.StrengthPoints
	}
	return 0
}

func (x *Item) GetSpellpowerPoints() uint64 {
	if x != nil {
		return x.SpellpowerPoints
	}
	return 0
}

func (x *Item) GetTypeDetails() isItem_TypeDetails {
	if x != nil {
		return x.TypeDetails
	}
	return nil
}

func (x *Item) GetConsumable() *ConsumableDetails {
	if x != nil {
		if x, ok := x.TypeDetails.(*Item_Consumable); ok {
			return x.Consumable
		}
	}
	return nil
}

func (x *Item) GetArmor() *ArmorDetails {
	if x != nil {
		if x, ok := x.TypeDetails.(*Item_Armor); ok {
			return x.Armor
		}
	}
	return nil
}

func (x *Item) GetWeapon() *WeaponDetails {
	if x != nil {
		if x, ok := x.TypeDetails.(*Item_Weapon); ok {
			return x.Weapon
		}
	}
	return nil
}

func (x *Item) GetGeneric() *GenericDetails {
	if x != nil {
		if x, ok := x.TypeDetails.(*Item_Generic); ok {
			return x.Generic
		}
	}
	return nil
}

type isItem_TypeDetails interface {
	isItem_TypeDetails()
}

type Item_Consumable struct {
	Consumable *ConsumableDetails `protobuf:"bytes,20,opt,name=consumable,proto3,oneof"`
}

type Item_Armor struct {
	Armor *ArmorDetails `protobuf:"bytes,21,opt,name=armor,proto3,oneof"`
}

type Item_Weapon struct {
	Weapon *WeaponDetails `protobuf:"bytes,22,opt,name=weapon,proto3,oneof"`
}

type Item_Generic struct {
	Generic *GenericDetails `protobuf:"bytes,23,opt,name=generic,proto3,oneof"`
}

func (*Item_Consumable) isItem_TypeDetails() {}

func (*Item_Armor) isItem_TypeDetails() {}

func (*Item_Weapon) isItem_TypeDetails() {}

func (*Item_Generic) isItem_TypeDetails() {}

// manual orm
type ConsumableDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uses          int32                  `protobuf:"varint,1,opt,name=uses,proto3" json:"uses,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Suffix        string                 `protobuf:"bytes,3,opt,name=suffix,proto3" json:"suffix,omitempty"`
	Healing       int32                  `protobuf:"varint,4,opt,name=healing,proto3" json:"healing,omitempty"`
	Power         int32                  `protobuf:"varint,5,opt,name=power,proto3" json:"power,omitempty"`
	Strength      int32                  `protobuf:"varint,6,opt,name=strength,proto3" json:"strength,omitempty"`
	Spellpower    int32                  `protobuf:"varint,7,opt,name=spellpower,proto3" json:"spellpower,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumableDetails) Reset() {
	*x = ConsumableDetails{}
	mi := &file_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumableDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumableDetails) ProtoMessage() {}

func (x *ConsumableDetails) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumableDetails.ProtoReflect.Descriptor instead.
func (*ConsumableDetails) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{6}
}

func (x *ConsumableDetails) GetUses() int32 {
	if x != nil {
		return x.Uses
	}
	return 0
}

func (x *ConsumableDetails) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ConsumableDetails) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *ConsumableDetails) GetHealing() int32 {
	if x != nil {
		return x.Healing
	}
	return 0
}

func (x *ConsumableDetails) GetPower() int32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *ConsumableDetails) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *ConsumableDetails) GetSpellpower() int32 {
	if x != nil {
		return x.Spellpower
	}
	return 0
}

type ArmorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EquipSlotId   int32                  `protobuf:"varint,1,opt,name=equip_slot_id,json=equipSlotId,proto3" json:"equip_slot_id,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Suffix        string                 `protobuf:"bytes,3,opt,name=suffix,proto3" json:"suffix,omitempty"`
	Armor         int32                  `protobuf:"varint,4,opt,name=armor,proto3" json:"armor,omitempty"`
	Health        int32                  `protobuf:"varint,5,opt,name=health,proto3" json:"health,omitempty"`
	Power         int32                  `protobuf:"varint,6,opt,name=power,proto3" json:"power,omitempty"`
	Strength      int32                  `protobuf:"varint,7,opt,name=strength,proto3" json:"strength,omitempty"`
	Spellpower    int32                  `protobuf:"varint,8,opt,name=spellpower,proto3" json:"spellpower,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArmorDetails) Reset() {
	*x = ArmorDetails{}
	mi := &file_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmorDetails) ProtoMessage() {}

func (x *ArmorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmorDetails.ProtoReflect.Descriptor instead.
func (*ArmorDetails) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{7}
}

func (x *ArmorDetails) GetEquipSlotId() int32 {
	if x != nil {
		return x.EquipSlotId
	}
	return 0
}

func (x *ArmorDetails) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ArmorDetails) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *ArmorDetails) GetArmor() int32 {
	if x != nil {
		return x.Armor
	}
	return 0
}

func (x *ArmorDetails) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *ArmorDetails) GetPower() int32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *ArmorDetails) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *ArmorDetails) GetSpellpower() int32 {
	if x != nil {
		return x.Spellpower
	}
	return 0
}

type WeaponDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseDamage    int32                  `protobuf:"varint,1,opt,name=base_damage,json=baseDamage,proto3" json:"base_damage,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Suffix        string                 `protobuf:"bytes,3,opt,name=suffix,proto3" json:"suffix,omitempty"`
	Strength      int32                  `protobuf:"varint,4,opt,name=strength,proto3" json:"strength,omitempty"`
	Spellpower    int32                  `protobuf:"varint,5,opt,name=spellpower,proto3" json:"spellpower,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeaponDetails) Reset() {
	*x = WeaponDetails{}
	mi := &file_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeaponDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeaponDetails) ProtoMessage() {}

func (x *WeaponDetails) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeaponDetails.ProtoReflect.Descriptor instead.
func (*WeaponDetails) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{8}
}

func (x *WeaponDetails) GetBaseDamage() int32 {
	if x != nil {
		return x.BaseDamage
	}
	return 0
}

func (x *WeaponDetails) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *WeaponDetails) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *WeaponDetails) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *WeaponDetails) GetSpellpower() int32 {
	if x != nil {
		return x.Spellpower
	}
	return 0
}

type GenericDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          string                 `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericDetails) Reset() {
	*x = GenericDetails{}
	mi := &file_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericDetails) ProtoMessage() {}

func (x *GenericDetails) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericDetails.ProtoReflect.Descriptor instead.
func (*GenericDetails) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{9}
}

func (x *GenericDetails) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// / id must be empty. storeserver sets id, created_at, updated_at
type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{10}
}

func (x *AddItemRequest) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type AddItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Created       *Item                  `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemResponse) Reset() {
	*x = AddItemResponse{}
	mi := &file_store_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResponse) ProtoMessage() {}

func (x *AddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemResponse.ProtoReflect.Descriptor instead.
func (*AddItemResponse) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{11}
}

func (x *AddItemResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddItemResponse) GetCreated() *Item {
	if x != nil {
		return x.Created
	}
	return nil
}

type BuyItemRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CharacterId    uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ItemTemplateId int64                  `protobuf:"varint,2,opt,name=item_template_id,json=itemTemplateId,proto3" json:"item_template_id,omitempty"`
	Quantity       int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BuyItemRequest) Reset() {
	*x = BuyItemRequest{}
	mi := &file_store_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyItemRequest) ProtoMessage() {}

func (x *BuyItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyItemRequest.ProtoReflect.Descriptor instead.
func (*BuyItemRequest) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{12}
}

func (x *BuyItemRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *BuyItemRequest) GetItemTemplateId() int64 {
	if x != nil {
		return x.ItemTemplateId
	}
	return 0
}

func (x *BuyItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BuyItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyItemResponse) Reset() {
	*x = BuyItemResponse{}
	mi := &file_store_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyItemResponse) ProtoMessage() {}

func (x *BuyItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyItemResponse.ProtoReflect.Descriptor instead.
func (*BuyItemResponse) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{13}
}

func (x *BuyItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuyItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_store_proto protoreflect.FileDescriptor

const file_store_proto_rawDesc = "" +
	"\n" +
	"\vstore.proto\x12\x05store\x1a\x1cgoogle/protobuf/struct.proto\",\n" +
	"\x16StoreListVendorRequest\x12\x12\n" +
	"\x04noop\x18\x01 \x01(\tR\x04noop\"~\n" +
	"\x06Vendor\x12\x1b\n" +
	"\tvendor_id\x18\x01 \x01(\x04R\bvendorId\x12\x1f\n" +
	"\vvendor_name\x18\x02 \x01(\tR\n" +
	"vendorName\x126\n" +
	"\x17vendor_ware_description\x18\x03 \x01(\tR\x15vendorWareDescription\"B\n" +
	"\x17StoreListVendorResponse\x12'\n" +
	"\avendors\x18\x01 \x03(\v2\r.store.VendorR\avendors\"\xa2\x02\n" +
	"\x1aStoreListVendorItemRequest\x12\x1b\n" +
	"\tvendor_id\x18\x01 \x01(\x04R\bvendorId\x12\x1d\n" +
	"\n" +
	"rarity_min\x18\x02 \x01(\x05R\trarityMin\x12\x1d\n" +
	"\n" +
	"rarity_max\x18\x03 \x01(\x05R\trarityMax\x12\x1c\n" +
	"\tstackable\x18\x04 \x01(\rR\tstackable\x12\x19\n" +
	"\bin_stock\x18\x05 \x01(\rR\ainStock\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\x12\x17\n" +
	"\asort_by\x18\f \x01(\tR\x06sortBy\x12\x1b\n" +
	"\tsort_desc\x18\r \x01(\bR\bsortDesc\"\\\n" +
	"\x16ListVendorItemResponse\x12!\n" +
	"\x05items\x18\x01 \x03(\v2\v.store.ItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\x98\x05\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\fitem_type_id\x18\x03 \x01(\rR\n" +
	"itemTypeId\x12\x16\n" +
	"\x06rarity\x18\x04 \x01(\rR\x06rarity\x12\x1c\n" +
	"\tstackable\x18\x05 \x01(\rR\tstackable\x12\x1d\n" +
	"\n" +
	"stack_size\x18\x06 \x01(\rR\tstackSize\x12$\n" +
	"\x0ebind_on_pickup\x18\a \x01(\rR\fbindOnPickup\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x123\n" +
	"\bmetadata\x18\t \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12#\n" +
	"\rhealth_points\x18\v \x01(\x04R\fhealthPoints\x12!\n" +
	"\fpower_points\x18\f \x01(\x04R\vpowerPoints\x12'\n" +
	"\x0fstrength_points\x18\r \x01(\x04R\x0estrengthPoints\x12+\n" +
	"\x11spellpower_points\x18\x0e \x01(\x04R\x10spellpowerPoints\x12:\n" +
	"\n" +
	"consumable\x18\x14 \x01(\v2\x18.store.ConsumableDetailsH\x00R\n" +
	"consumable\x12+\n" +
	"\x05armor\x18\x15 \x01(\v2\x13.store.ArmorDetailsH\x00R\x05armor\x12.\n" +
	"\x06weapon\x18\x16 \x01(\v2\x14.store.WeaponDetailsH\x00R\x06weapon\x121\n" +
	"\ageneric\x18\x17 \x01(\v2\x15.store.GenericDetailsH\x00R\agenericB\x0e\n" +
	"\ftype_details\"\xc3\x01\n" +
	"\x11ConsumableDetails\x12\x12\n" +
	"\x04uses\x18\x01 \x01(\x05R\x04uses\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06suffix\x18\x03 \x01(\tR\x06suffix\x12\x18\n" +
	"\ahealing\x18\x04 \x01(\x05R\ahealing\x12\x14\n" +
	"\x05power\x18\x05 \x01(\x05R\x05power\x12\x1a\n" +
	"\bstrength\x18\x06 \x01(\x05R\bstrength\x12\x1e\n" +
	"\n" +
	"spellpower\x18\a \x01(\x05R\n" +
	"spellpower\"\xe2\x01\n" +
	"\fArmorDetails\x12\"\n" +
	"\requip_slot_id\x18\x01 \x01(\x05R\vequipSlotId\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06suffix\x18\x03 \x01(\tR\x06suffix\x12\x14\n" +
	"\x05armor\x18\x04 \x01(\x05R\x05armor\x12\x16\n" +
	"\x06health\x18\x05 \x01(\x05R\x06health\x12\x14\n" +
	"\x05power\x18\x06 \x01(\x05R\x05power\x12\x1a\n" +
	"\bstrength\x18\a \x01(\x05R\bstrength\x12\x1e\n" +
	"\n" +
	"spellpower\x18\b \x01(\x05R\n" +
	"spellpower\"\x9c\x01\n" +
	"\rWeaponDetails\x12\x1f\n" +
	"\vbase_damage\x18\x01 \x01(\x05R\n" +
	"baseDamage\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06suffix\x18\x03 \x01(\tR\x06suffix\x12\x1a\n" +
	"\bstrength\x18\x04 \x01(\x05R\bstrength\x12\x1e\n" +
	"\n" +
	"spellpower\x18\x05 \x01(\x05R\n" +
	"spellpower\"$\n" +
	"\x0eGenericDetails\x12\x12\n" +
	"\x04note\x18\x01 \x01(\tR\x04note\"1\n" +
	"\x0eAddItemRequest\x12\x1f\n" +
	"\x04item\x18\x01 \x01(\v2\v.store.ItemR\x04item\"H\n" +
	"\x0fAddItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\acreated\x18\x02 \x01(\v2\v.store.ItemR\acreated\"y\n" +
	"\x0eBuyItemRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\x12(\n" +
	"\x10item_template_id\x18\x02 \x01(\x03R\x0eitemTemplateId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"E\n" +
	"\x0fBuyItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9e\x02\n" +
	"\x05Store\x12L\n" +
	"\vListVendors\x12\x1d.store.StoreListVendorRequest\x1a\x1e.store.StoreListVendorResponse\x12S\n" +
	"\x0fListVendorItems\x12!.store.StoreListVendorItemRequest\x1a\x1d.store.ListVendorItemResponse\x128\n" +
	"\aAddItem\x12\x15.store.AddItemRequest\x1a\x16.store.AddItemResponse\x128\n" +
	"\aBuyItem\x12\x15.store.BuyItemRequest\x1a\x16.store.BuyItemResponseB\x13Z\x11proto/store;storeb\x06proto3"

var (
	file_store_proto_rawDescOnce sync.Once
	file_store_proto_rawDescData []byte
)

func file_store_proto_rawDescGZIP() []byte {
	file_store_proto_rawDescOnce.Do(func() {
		file_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_proto_rawDesc), len(file_store_proto_rawDesc)))
	})
	return file_store_proto_rawDescData
}

var file_store_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_store_proto_goTypes = []any{
	(*StoreListVendorRequest)(nil),     // 0: store.StoreListVendorRequest
	(*Vendor)(nil),                     // 1: store.Vendor
	(*StoreListVendorResponse)(nil),    // 2: store.StoreListVendorResponse
	(*StoreListVendorItemRequest)(nil), // 3: store.StoreListVendorItemRequest
	(*ListVendorItemResponse)(nil),     // 4: store.ListVendorItemResponse
	(*Item)(nil),                       // 5: store.Item
	(*ConsumableDetails)(nil),          // 6: store.ConsumableDetails
	(*ArmorDetails)(nil),               // 7: store.ArmorDetails
	(*WeaponDetails)(nil),              // 8: store.WeaponDetails
	(*GenericDetails)(nil),             // 9: store.GenericDetails
	(*AddItemRequest)(nil),             // 10: store.AddItemRequest
	(*AddItemResponse)(nil),            // 11: store.AddItemResponse
	(*BuyItemRequest)(nil),             // 12: store.BuyItemRequest
	(*BuyItemResponse)(nil),            // 13: store.BuyItemResponse
	(*structpb.Struct)(nil),            // 14: google.protobuf.Struct
}
var file_store_proto_depIdxs = []int32{
	1,  // 0: store.StoreListVendorResponse.vendors:type_name -> store.Vendor
	5,  // 1: store.ListVendorItemResponse.items:type_name -> store.Item
	14, // 2: store.Item.metadata:type_name -> google.protobuf.Struct
	6,  // 3: store.Item.consumable:type_name -> store.ConsumableDetails
	7,  // 4: store.Item.armor:type_name -> store.ArmorDetails
	8,  // 5: store.Item.weapon:type_name -> store.WeaponDetails
	9,  // 6: store.Item.generic:type_name -> store.GenericDetails
	5,  // 7: store.AddItemRequest.item:type_name -> store.Item
	5,  // 8: store.AddItemResponse.created:type_name -> store.Item
	0,  // 9: store.Store.ListVendors:input_type -> store.StoreListVendorRequest
	3,  // 10: store.Store.ListVendorItems:input_type -> store.StoreListVendorItemRequest
	10, // 11: store.Store.AddItem:input_type -> store.AddItemRequest
	12, // 12: store.Store.BuyItem:input_type -> store.BuyItemRequest
	2,  // 13: store.Store.ListVendors:output_type -> store.StoreListVendorResponse
	4,  // 14: store.Store.ListVendorItems:output_type -> store.ListVendorItemResponse
	11, // 15: store.Store.AddItem:output_type -> store.AddItemResponse
	13, // 16: store.Store.BuyItem:output_type -> store.BuyItemResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_store_proto_init() }
func file_store_proto_init() {
	if File_store_proto != nil {
		return
	}
	file_store_proto_msgTypes[5].OneofWrappers = []any{
		(*Item_Consumable)(nil),
		(*Item_Armor)(nil),
		(*Item_Weapon)(nil),
		(*Item_Generic)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_proto_rawDesc), len(file_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_store_proto_goTypes,
		DependencyIndexes: file_store_proto_depIdxs,
		MessageInfos:      file_store_proto_msgTypes,
	}.Build()
	File_store_proto = out.File
	file_store_proto_goTypes = nil
	file_store_proto_depIdxs = nil
}
