// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: store/store.proto

package store

import (
	repo "github.com/komadiina/spelltext/proto/repo"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreListVendorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Noop          string                 `protobuf:"bytes,1,opt,name=noop,proto3" json:"noop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreListVendorRequest) Reset() {
	*x = StoreListVendorRequest{}
	mi := &file_store_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreListVendorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreListVendorRequest) ProtoMessage() {}

func (x *StoreListVendorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreListVendorRequest.ProtoReflect.Descriptor instead.
func (*StoreListVendorRequest) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{0}
}

func (x *StoreListVendorRequest) GetNoop() string {
	if x != nil {
		return x.Noop
	}
	return ""
}

type StoreListVendorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendors       []*repo.Vendor         `protobuf:"bytes,1,rep,name=vendors,proto3" json:"vendors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreListVendorResponse) Reset() {
	*x = StoreListVendorResponse{}
	mi := &file_store_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreListVendorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreListVendorResponse) ProtoMessage() {}

func (x *StoreListVendorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreListVendorResponse.ProtoReflect.Descriptor instead.
func (*StoreListVendorResponse) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{1}
}

func (x *StoreListVendorResponse) GetVendors() []*repo.Vendor {
	if x != nil {
		return x.Vendors
	}
	return nil
}

type StoreListVendorItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VendorId      uint64                 `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"` // 0 = any
	RarityMin     int32                  `protobuf:"varint,2,opt,name=rarity_min,json=rarityMin,proto3" json:"rarity_min,omitempty"`
	RarityMax     int32                  `protobuf:"varint,3,opt,name=rarity_max,json=rarityMax,proto3" json:"rarity_max,omitempty"`
	Stackable     uint32                 `protobuf:"varint,4,opt,name=stackable,proto3" json:"stackable,omitempty"`
	InStock       uint32                 `protobuf:"varint,5,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	PageSize      int32                  `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	SortBy        string                 `protobuf:"bytes,12,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"` // "name", "rarity", "stock"
	SortDesc      bool                   `protobuf:"varint,13,opt,name=sort_desc,json=sortDesc,proto3" json:"sort_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreListVendorItemRequest) Reset() {
	*x = StoreListVendorItemRequest{}
	mi := &file_store_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreListVendorItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreListVendorItemRequest) ProtoMessage() {}

func (x *StoreListVendorItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreListVendorItemRequest.ProtoReflect.Descriptor instead.
func (*StoreListVendorItemRequest) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{2}
}

func (x *StoreListVendorItemRequest) GetVendorId() uint64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *StoreListVendorItemRequest) GetRarityMin() int32 {
	if x != nil {
		return x.RarityMin
	}
	return 0
}

func (x *StoreListVendorItemRequest) GetRarityMax() int32 {
	if x != nil {
		return x.RarityMax
	}
	return 0
}

func (x *StoreListVendorItemRequest) GetStackable() uint32 {
	if x != nil {
		return x.Stackable
	}
	return 0
}

func (x *StoreListVendorItemRequest) GetInStock() uint32 {
	if x != nil {
		return x.InStock
	}
	return 0
}

func (x *StoreListVendorItemRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *StoreListVendorItemRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *StoreListVendorItemRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *StoreListVendorItemRequest) GetSortDesc() bool {
	if x != nil {
		return x.SortDesc
	}
	return false
}

type ListVendorItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*repo.Item           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVendorItemResponse) Reset() {
	*x = ListVendorItemResponse{}
	mi := &file_store_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVendorItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVendorItemResponse) ProtoMessage() {}

func (x *ListVendorItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVendorItemResponse.ProtoReflect.Descriptor instead.
func (*ListVendorItemResponse) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{3}
}

func (x *ListVendorItemResponse) GetItems() []*repo.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListVendorItemResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GenericDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          string                 `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericDetails) Reset() {
	*x = GenericDetails{}
	mi := &file_store_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericDetails) ProtoMessage() {}

func (x *GenericDetails) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericDetails.ProtoReflect.Descriptor instead.
func (*GenericDetails) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{4}
}

func (x *GenericDetails) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type BuyItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ItemIds       []uint64               `protobuf:"varint,2,rep,packed,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyItemRequest) Reset() {
	*x = BuyItemRequest{}
	mi := &file_store_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyItemRequest) ProtoMessage() {}

func (x *BuyItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyItemRequest.ProtoReflect.Descriptor instead.
func (*BuyItemRequest) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{5}
}

func (x *BuyItemRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *BuyItemRequest) GetItemIds() []uint64 {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

func (x *BuyItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BuyItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyItemResponse) Reset() {
	*x = BuyItemResponse{}
	mi := &file_store_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyItemResponse) ProtoMessage() {}

func (x *BuyItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyItemResponse.ProtoReflect.Descriptor instead.
func (*BuyItemResponse) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{6}
}

func (x *BuyItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuyItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SellItemRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CharacterId    uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ItemInstanceId int64                  `protobuf:"varint,2,opt,name=item_instance_id,json=itemInstanceId,proto3" json:"item_instance_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SellItemRequest) Reset() {
	*x = SellItemRequest{}
	mi := &file_store_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellItemRequest) ProtoMessage() {}

func (x *SellItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellItemRequest.ProtoReflect.Descriptor instead.
func (*SellItemRequest) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{7}
}

func (x *SellItemRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *SellItemRequest) GetItemInstanceId() int64 {
	if x != nil {
		return x.ItemInstanceId
	}
	return 0
}

type SellItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellItemResponse) Reset() {
	*x = SellItemResponse{}
	mi := &file_store_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellItemResponse) ProtoMessage() {}

func (x *SellItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellItemResponse.ProtoReflect.Descriptor instead.
func (*SellItemResponse) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{8}
}

func (x *SellItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SellItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_store_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{9}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_store_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{10}
}

var File_store_store_proto protoreflect.FileDescriptor

const file_store_store_proto_rawDesc = "" +
	"\n" +
	"\x11store/store.proto\x12\x05store\x1a\x0frepo/repo.proto\",\n" +
	"\x16StoreListVendorRequest\x12\x12\n" +
	"\x04noop\x18\x01 \x01(\tR\x04noop\"A\n" +
	"\x17StoreListVendorResponse\x12&\n" +
	"\avendors\x18\x01 \x03(\v2\f.repo.VendorR\avendors\"\xa2\x02\n" +
	"\x1aStoreListVendorItemRequest\x12\x1b\n" +
	"\tvendor_id\x18\x01 \x01(\x04R\bvendorId\x12\x1d\n" +
	"\n" +
	"rarity_min\x18\x02 \x01(\x05R\trarityMin\x12\x1d\n" +
	"\n" +
	"rarity_max\x18\x03 \x01(\x05R\trarityMax\x12\x1c\n" +
	"\tstackable\x18\x04 \x01(\rR\tstackable\x12\x19\n" +
	"\bin_stock\x18\x05 \x01(\rR\ainStock\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\x12\x17\n" +
	"\asort_by\x18\f \x01(\tR\x06sortBy\x12\x1b\n" +
	"\tsort_desc\x18\r \x01(\bR\bsortDesc\"[\n" +
	"\x16ListVendorItemResponse\x12 \n" +
	"\x05items\x18\x01 \x03(\v2\n" +
	".repo.ItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"$\n" +
	"\x0eGenericDetails\x12\x12\n" +
	"\x04note\x18\x01 \x01(\tR\x04note\"j\n" +
	"\x0eBuyItemRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\x12\x19\n" +
	"\bitem_ids\x18\x02 \x03(\x04R\aitemIds\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"E\n" +
	"\x0fBuyItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"^\n" +
	"\x0fSellItemRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\x12(\n" +
	"\x10item_instance_id\x18\x02 \x01(\x03R\x0eitemInstanceId\"F\n" +
	"\x10SellItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse2\xd3\x02\n" +
	"\x05Store\x12/\n" +
	"\x04Ping\x12\x12.store.PingRequest\x1a\x13.store.PingResponse\x12L\n" +
	"\vListVendors\x12\x1d.store.StoreListVendorRequest\x1a\x1e.store.StoreListVendorResponse\x12S\n" +
	"\x0fListVendorItems\x12!.store.StoreListVendorItemRequest\x1a\x1d.store.ListVendorItemResponse\x129\n" +
	"\bBuyItems\x12\x15.store.BuyItemRequest\x1a\x16.store.BuyItemResponse\x12;\n" +
	"\bSellItem\x12\x16.store.SellItemRequest\x1a\x17.store.SellItemResponseB2Z0github.com/komadiina/spelltext/proto/store;storeb\x06proto3"

var (
	file_store_store_proto_rawDescOnce sync.Once
	file_store_store_proto_rawDescData []byte
)

func file_store_store_proto_rawDescGZIP() []byte {
	file_store_store_proto_rawDescOnce.Do(func() {
		file_store_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_store_proto_rawDesc), len(file_store_store_proto_rawDesc)))
	})
	return file_store_store_proto_rawDescData
}

var file_store_store_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_store_store_proto_goTypes = []any{
	(*StoreListVendorRequest)(nil),     // 0: store.StoreListVendorRequest
	(*StoreListVendorResponse)(nil),    // 1: store.StoreListVendorResponse
	(*StoreListVendorItemRequest)(nil), // 2: store.StoreListVendorItemRequest
	(*ListVendorItemResponse)(nil),     // 3: store.ListVendorItemResponse
	(*GenericDetails)(nil),             // 4: store.GenericDetails
	(*BuyItemRequest)(nil),             // 5: store.BuyItemRequest
	(*BuyItemResponse)(nil),            // 6: store.BuyItemResponse
	(*SellItemRequest)(nil),            // 7: store.SellItemRequest
	(*SellItemResponse)(nil),           // 8: store.SellItemResponse
	(*PingRequest)(nil),                // 9: store.PingRequest
	(*PingResponse)(nil),               // 10: store.PingResponse
	(*repo.Vendor)(nil),                // 11: repo.Vendor
	(*repo.Item)(nil),                  // 12: repo.Item
}
var file_store_store_proto_depIdxs = []int32{
	11, // 0: store.StoreListVendorResponse.vendors:type_name -> repo.Vendor
	12, // 1: store.ListVendorItemResponse.items:type_name -> repo.Item
	9,  // 2: store.Store.Ping:input_type -> store.PingRequest
	0,  // 3: store.Store.ListVendors:input_type -> store.StoreListVendorRequest
	2,  // 4: store.Store.ListVendorItems:input_type -> store.StoreListVendorItemRequest
	5,  // 5: store.Store.BuyItems:input_type -> store.BuyItemRequest
	7,  // 6: store.Store.SellItem:input_type -> store.SellItemRequest
	10, // 7: store.Store.Ping:output_type -> store.PingResponse
	1,  // 8: store.Store.ListVendors:output_type -> store.StoreListVendorResponse
	3,  // 9: store.Store.ListVendorItems:output_type -> store.ListVendorItemResponse
	6,  // 10: store.Store.BuyItems:output_type -> store.BuyItemResponse
	8,  // 11: store.Store.SellItem:output_type -> store.SellItemResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_store_store_proto_init() }
func file_store_store_proto_init() {
	if File_store_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_store_proto_rawDesc), len(file_store_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_store_store_proto_goTypes,
		DependencyIndexes: file_store_store_proto_depIdxs,
		MessageInfos:      file_store_store_proto_msgTypes,
	}.Build()
	File_store_store_proto = out.File
	file_store_store_proto_goTypes = nil
	file_store_store_proto_depIdxs = nil
}
