apiVersion: v2
name: spelltext
description: "@gh/komadiina/spelltext: k8s-chart"
type: application
version: 0.3.0
appVersion: "1.16.0"

dependencies:
  - name: nats
    version: 1.3.14
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    condition: nats.enabled
  - name: postgresql-ha
    version: 16.3.2
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql-ha.enabled
  - name: loki-stack
    version: 2.10.2
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana-loki-stack.enabled
