// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InventoryBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Character     string                 `protobuf:"bytes,2,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryBalanceRequest) Reset() {
	*x = InventoryBalanceRequest{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryBalanceRequest) ProtoMessage() {}

func (x *InventoryBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryBalanceRequest.ProtoReflect.Descriptor instead.
func (*InventoryBalanceRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *InventoryBalanceRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *InventoryBalanceRequest) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

type InventoryBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gold          uint64                 `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`
	Tokens        uint64                 `protobuf:"varint,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryBalanceResponse) Reset() {
	*x = InventoryBalanceResponse{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryBalanceResponse) ProtoMessage() {}

func (x *InventoryBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryBalanceResponse.ProtoReflect.Descriptor instead.
func (*InventoryBalanceResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *InventoryBalanceResponse) GetGold() uint64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *InventoryBalanceResponse) GetTokens() uint64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

type SellItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Character     string                 `protobuf:"bytes,2,opt,name=character,proto3" json:"character,omitempty"`
	ItemId        uint64                 `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellItemRequest) Reset() {
	*x = SellItemRequest{}
	mi := &file_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellItemRequest) ProtoMessage() {}

func (x *SellItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellItemRequest.ProtoReflect.Descriptor instead.
func (*SellItemRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *SellItemRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SellItemRequest) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *SellItemRequest) GetItemId() uint64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type SellItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellItemResponse) Reset() {
	*x = SellItemResponse{}
	mi := &file_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellItemResponse) ProtoMessage() {}

func (x *SellItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellItemResponse.ProtoReflect.Descriptor instead.
func (*SellItemResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *SellItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SellItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n" +
	"\x0finventory.proto\x12\tinventory\"S\n" +
	"\x17InventoryBalanceRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1c\n" +
	"\tcharacter\x18\x02 \x01(\tR\tcharacter\"F\n" +
	"\x18InventoryBalanceResponse\x12\x12\n" +
	"\x04gold\x18\x01 \x01(\x04R\x04gold\x12\x16\n" +
	"\x06tokens\x18\x02 \x01(\x04R\x06tokens\"d\n" +
	"\x0fSellItemRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1c\n" +
	"\tcharacter\x18\x02 \x01(\tR\tcharacter\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\x04R\x06itemId\"F\n" +
	"\x10SellItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa7\x01\n" +
	"\tInventory\x12U\n" +
	"\n" +
	"GetBalance\x12\".inventory.InventoryBalanceRequest\x1a#.inventory.InventoryBalanceResponse\x12C\n" +
	"\bSellItem\x12\x1a.inventory.SellItemRequest\x1a\x1b.inventory.SellItemResponseB\x1bZ\x19proto/inventory;inventoryb\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_inventory_proto_goTypes = []any{
	(*InventoryBalanceRequest)(nil),  // 0: inventory.InventoryBalanceRequest
	(*InventoryBalanceResponse)(nil), // 1: inventory.InventoryBalanceResponse
	(*SellItemRequest)(nil),          // 2: inventory.SellItemRequest
	(*SellItemResponse)(nil),         // 3: inventory.SellItemResponse
}
var file_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.Inventory.GetBalance:input_type -> inventory.InventoryBalanceRequest
	2, // 1: inventory.Inventory.SellItem:input_type -> inventory.SellItemRequest
	1, // 2: inventory.Inventory.GetBalance:output_type -> inventory.InventoryBalanceResponse
	3, // 3: inventory.Inventory.SellItem:output_type -> inventory.SellItemResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
