// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: inventory/inventory.proto

package inventory

import (
	repo "github.com/komadiina/spelltext/proto/repo"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InventoryBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Character     string                 `protobuf:"bytes,2,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryBalanceRequest) Reset() {
	*x = InventoryBalanceRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryBalanceRequest) ProtoMessage() {}

func (x *InventoryBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryBalanceRequest.ProtoReflect.Descriptor instead.
func (*InventoryBalanceRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *InventoryBalanceRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *InventoryBalanceRequest) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

type InventoryBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gold          uint64                 `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`
	Tokens        uint64                 `protobuf:"varint,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryBalanceResponse) Reset() {
	*x = InventoryBalanceResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryBalanceResponse) ProtoMessage() {}

func (x *InventoryBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryBalanceResponse.ProtoReflect.Descriptor instead.
func (*InventoryBalanceResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *InventoryBalanceResponse) GetGold() uint64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *InventoryBalanceResponse) GetTokens() uint64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

type SellItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Character     string                 `protobuf:"bytes,2,opt,name=character,proto3" json:"character,omitempty"`
	ItemId        uint64                 `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellItemRequest) Reset() {
	*x = SellItemRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellItemRequest) ProtoMessage() {}

func (x *SellItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellItemRequest.ProtoReflect.Descriptor instead.
func (*SellItemRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *SellItemRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SellItemRequest) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *SellItemRequest) GetItemId() uint64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type SellItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellItemResponse) Reset() {
	*x = SellItemResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellItemResponse) ProtoMessage() {}

func (x *SellItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellItemResponse.ProtoReflect.Descriptor instead.
func (*SellItemResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *SellItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SellItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddItemsToBackpackRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CharacterId     uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ItemInstanceIds []uint64               `protobuf:"varint,2,rep,packed,name=item_instance_ids,json=itemInstanceIds,proto3" json:"item_instance_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddItemsToBackpackRequest) Reset() {
	*x = AddItemsToBackpackRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemsToBackpackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemsToBackpackRequest) ProtoMessage() {}

func (x *AddItemsToBackpackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemsToBackpackRequest.ProtoReflect.Descriptor instead.
func (*AddItemsToBackpackRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *AddItemsToBackpackRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *AddItemsToBackpackRequest) GetItemInstanceIds() []uint64 {
	if x != nil {
		return x.ItemInstanceIds
	}
	return nil
}

type AddItemsToBackpackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemsToBackpackResponse) Reset() {
	*x = AddItemsToBackpackResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemsToBackpackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemsToBackpackResponse) ProtoMessage() {}

func (x *AddItemsToBackpackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemsToBackpackResponse.ProtoReflect.Descriptor instead.
func (*AddItemsToBackpackResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *AddItemsToBackpackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddItemsToBackpackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListBackpackItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackpackItemsRequest) Reset() {
	*x = ListBackpackItemsRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackpackItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackpackItemsRequest) ProtoMessage() {}

func (x *ListBackpackItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackpackItemsRequest.ProtoReflect.Descriptor instead.
func (*ListBackpackItemsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ListBackpackItemsRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type ListBackpackItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemInstances []*repo.ItemInstance   `protobuf:"bytes,1,rep,name=item_instances,json=itemInstances,proto3" json:"item_instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackpackItemsResponse) Reset() {
	*x = ListBackpackItemsResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackpackItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackpackItemsResponse) ProtoMessage() {}

func (x *ListBackpackItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackpackItemsResponse.ProtoReflect.Descriptor instead.
func (*ListBackpackItemsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *ListBackpackItemsResponse) GetItemInstances() []*repo.ItemInstance {
	if x != nil {
		return x.ItemInstances
	}
	return nil
}

var File_inventory_inventory_proto protoreflect.FileDescriptor

const file_inventory_inventory_proto_rawDesc = "" +
	"\n" +
	"\x19inventory/inventory.proto\x12\tinventory\x1a\x0frepo/repo.proto\"S\n" +
	"\x17InventoryBalanceRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1c\n" +
	"\tcharacter\x18\x02 \x01(\tR\tcharacter\"F\n" +
	"\x18InventoryBalanceResponse\x12\x12\n" +
	"\x04gold\x18\x01 \x01(\x04R\x04gold\x12\x16\n" +
	"\x06tokens\x18\x02 \x01(\x04R\x06tokens\"d\n" +
	"\x0fSellItemRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1c\n" +
	"\tcharacter\x18\x02 \x01(\tR\tcharacter\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\x04R\x06itemId\"F\n" +
	"\x10SellItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"j\n" +
	"\x19AddItemsToBackpackRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\x12*\n" +
	"\x11item_instance_ids\x18\x02 \x03(\x04R\x0fitemInstanceIds\"P\n" +
	"\x1aAddItemsToBackpackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\x18ListBackpackItemsRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\"V\n" +
	"\x19ListBackpackItemsResponse\x129\n" +
	"\x0eitem_instances\x18\x01 \x03(\v2\x12.repo.ItemInstanceR\ritemInstances2\xea\x02\n" +
	"\tInventory\x12U\n" +
	"\n" +
	"GetBalance\x12\".inventory.InventoryBalanceRequest\x1a#.inventory.InventoryBalanceResponse\x12C\n" +
	"\bSellItem\x12\x1a.inventory.SellItemRequest\x1a\x1b.inventory.SellItemResponse\x12a\n" +
	"\x12AddItemsToBackpack\x12$.inventory.AddItemsToBackpackRequest\x1a%.inventory.AddItemsToBackpackResponse\x12^\n" +
	"\x11ListBackpackItems\x12#.inventory.ListBackpackItemsRequest\x1a$.inventory.ListBackpackItemsResponseB:Z8github.com/komadiina/spelltext/proto/inventory;inventoryb\x06proto3"

var (
	file_inventory_inventory_proto_rawDescOnce sync.Once
	file_inventory_inventory_proto_rawDescData []byte
)

func file_inventory_inventory_proto_rawDescGZIP() []byte {
	file_inventory_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_inventory_proto_rawDesc), len(file_inventory_inventory_proto_rawDesc)))
	})
	return file_inventory_inventory_proto_rawDescData
}

var file_inventory_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_inventory_inventory_proto_goTypes = []any{
	(*InventoryBalanceRequest)(nil),    // 0: inventory.InventoryBalanceRequest
	(*InventoryBalanceResponse)(nil),   // 1: inventory.InventoryBalanceResponse
	(*SellItemRequest)(nil),            // 2: inventory.SellItemRequest
	(*SellItemResponse)(nil),           // 3: inventory.SellItemResponse
	(*AddItemsToBackpackRequest)(nil),  // 4: inventory.AddItemsToBackpackRequest
	(*AddItemsToBackpackResponse)(nil), // 5: inventory.AddItemsToBackpackResponse
	(*ListBackpackItemsRequest)(nil),   // 6: inventory.ListBackpackItemsRequest
	(*ListBackpackItemsResponse)(nil),  // 7: inventory.ListBackpackItemsResponse
	(*repo.ItemInstance)(nil),          // 8: repo.ItemInstance
}
var file_inventory_inventory_proto_depIdxs = []int32{
	8, // 0: inventory.ListBackpackItemsResponse.item_instances:type_name -> repo.ItemInstance
	0, // 1: inventory.Inventory.GetBalance:input_type -> inventory.InventoryBalanceRequest
	2, // 2: inventory.Inventory.SellItem:input_type -> inventory.SellItemRequest
	4, // 3: inventory.Inventory.AddItemsToBackpack:input_type -> inventory.AddItemsToBackpackRequest
	6, // 4: inventory.Inventory.ListBackpackItems:input_type -> inventory.ListBackpackItemsRequest
	1, // 5: inventory.Inventory.GetBalance:output_type -> inventory.InventoryBalanceResponse
	3, // 6: inventory.Inventory.SellItem:output_type -> inventory.SellItemResponse
	5, // 7: inventory.Inventory.AddItemsToBackpack:output_type -> inventory.AddItemsToBackpackResponse
	7, // 8: inventory.Inventory.ListBackpackItems:output_type -> inventory.ListBackpackItemsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inventory_inventory_proto_init() }
func file_inventory_inventory_proto_init() {
	if File_inventory_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_inventory_proto_rawDesc), len(file_inventory_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_inventory_proto_msgTypes,
	}.Build()
	File_inventory_inventory_proto = out.File
	file_inventory_inventory_proto_goTypes = nil
	file_inventory_inventory_proto_depIdxs = nil
}
