// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: char/char.proto

package char

import (
	health "github.com/komadiina/spelltext/proto/health"
	repo "github.com/komadiina/spelltext/proto/repo"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListHeroesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHeroesRequest) Reset() {
	*x = ListHeroesRequest{}
	mi := &file_char_char_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHeroesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHeroesRequest) ProtoMessage() {}

func (x *ListHeroesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHeroesRequest.ProtoReflect.Descriptor instead.
func (*ListHeroesRequest) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{0}
}

type ListHeroesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Heroes        []*repo.Hero           `protobuf:"bytes,1,rep,name=heroes,proto3" json:"heroes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHeroesResponse) Reset() {
	*x = ListHeroesResponse{}
	mi := &file_char_char_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHeroesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHeroesResponse) ProtoMessage() {}

func (x *ListHeroesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHeroesResponse.ProtoReflect.Descriptor instead.
func (*ListHeroesResponse) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{1}
}

func (x *ListHeroesResponse) GetHeroes() []*repo.Hero {
	if x != nil {
		return x.Heroes
	}
	return nil
}

type ListCharactersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharactersRequest) Reset() {
	*x = ListCharactersRequest{}
	mi := &file_char_char_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharactersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharactersRequest) ProtoMessage() {}

func (x *ListCharactersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharactersRequest.ProtoReflect.Descriptor instead.
func (*ListCharactersRequest) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{2}
}

func (x *ListCharactersRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ListCharactersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*repo.Character      `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharactersResponse) Reset() {
	*x = ListCharactersResponse{}
	mi := &file_char_char_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharactersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharactersResponse) ProtoMessage() {}

func (x *ListCharactersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharactersResponse.ProtoReflect.Descriptor instead.
func (*ListCharactersResponse) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{3}
}

func (x *ListCharactersResponse) GetCharacters() []*repo.Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

type SetSelectedCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CharacterId   uint64                 `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSelectedCharacterRequest) Reset() {
	*x = SetSelectedCharacterRequest{}
	mi := &file_char_char_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSelectedCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSelectedCharacterRequest) ProtoMessage() {}

func (x *SetSelectedCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSelectedCharacterRequest.ProtoReflect.Descriptor instead.
func (*SetSelectedCharacterRequest) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{4}
}

func (x *SetSelectedCharacterRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetSelectedCharacterRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type SetSelectedCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSelectedCharacterResponse) Reset() {
	*x = SetSelectedCharacterResponse{}
	mi := &file_char_char_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSelectedCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSelectedCharacterResponse) ProtoMessage() {}

func (x *SetSelectedCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSelectedCharacterResponse.ProtoReflect.Descriptor instead.
func (*SetSelectedCharacterResponse) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{5}
}

func (x *SetSelectedCharacterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetSelectedCharacterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLastSelectedCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastSelectedCharacterRequest) Reset() {
	*x = GetLastSelectedCharacterRequest{}
	mi := &file_char_char_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastSelectedCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastSelectedCharacterRequest) ProtoMessage() {}

func (x *GetLastSelectedCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastSelectedCharacterRequest.ProtoReflect.Descriptor instead.
func (*GetLastSelectedCharacterRequest) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{6}
}

func (x *GetLastSelectedCharacterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetLastSelectedCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *repo.Character        `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastSelectedCharacterResponse) Reset() {
	*x = GetLastSelectedCharacterResponse{}
	mi := &file_char_char_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastSelectedCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastSelectedCharacterResponse) ProtoMessage() {}

func (x *GetLastSelectedCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastSelectedCharacterResponse.ProtoReflect.Descriptor instead.
func (*GetLastSelectedCharacterResponse) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{7}
}

func (x *GetLastSelectedCharacterResponse) GetCharacter() *repo.Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type GetCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterRequest) Reset() {
	*x = GetCharacterRequest{}
	mi := &file_char_char_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterRequest) ProtoMessage() {}

func (x *GetCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterRequest) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{8}
}

func (x *GetCharacterRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type GetCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *repo.Character        `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterResponse) Reset() {
	*x = GetCharacterResponse{}
	mi := &file_char_char_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterResponse) ProtoMessage() {}

func (x *GetCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterResponse.ProtoReflect.Descriptor instead.
func (*GetCharacterResponse) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{9}
}

func (x *GetCharacterResponse) GetCharacter() *repo.Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type CreateCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Hero          *repo.Hero             `protobuf:"bytes,2,opt,name=hero,proto3" json:"hero,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterRequest) Reset() {
	*x = CreateCharacterRequest{}
	mi := &file_char_char_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterRequest) ProtoMessage() {}

func (x *CreateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterRequest.ProtoReflect.Descriptor instead.
func (*CreateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCharacterRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCharacterRequest) GetHero() *repo.Hero {
	if x != nil {
		return x.Hero
	}
	return nil
}

func (x *CreateCharacterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Character     *repo.Character        `protobuf:"bytes,3,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterResponse) Reset() {
	*x = CreateCharacterResponse{}
	mi := &file_char_char_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterResponse) ProtoMessage() {}

func (x *CreateCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterResponse.ProtoReflect.Descriptor instead.
func (*CreateCharacterResponse) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{11}
}

func (x *CreateCharacterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateCharacterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateCharacterResponse) GetCharacter() *repo.Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type DeleteCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterRequest) Reset() {
	*x = DeleteCharacterRequest{}
	mi := &file_char_char_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterRequest) ProtoMessage() {}

func (x *DeleteCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterRequest.ProtoReflect.Descriptor instead.
func (*DeleteCharacterRequest) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCharacterRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type DeleteCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterResponse) Reset() {
	*x = DeleteCharacterResponse{}
	mi := &file_char_char_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterResponse) ProtoMessage() {}

func (x *DeleteCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterResponse.ProtoReflect.Descriptor instead.
func (*DeleteCharacterResponse) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteCharacterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCharacterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ToggleEquipRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CharacterId    uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ItemInstanceId uint64                 `protobuf:"varint,2,opt,name=item_instance_id,json=itemInstanceId,proto3" json:"item_instance_id,omitempty"`
	EquipSlotId    uint64                 `protobuf:"varint,3,opt,name=equip_slot_id,json=equipSlotId,proto3" json:"equip_slot_id,omitempty"`
	ShouldEquip    bool                   `protobuf:"varint,4,opt,name=shouldEquip,proto3" json:"shouldEquip,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToggleEquipRequest) Reset() {
	*x = ToggleEquipRequest{}
	mi := &file_char_char_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleEquipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleEquipRequest) ProtoMessage() {}

func (x *ToggleEquipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleEquipRequest.ProtoReflect.Descriptor instead.
func (*ToggleEquipRequest) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{14}
}

func (x *ToggleEquipRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *ToggleEquipRequest) GetItemInstanceId() uint64 {
	if x != nil {
		return x.ItemInstanceId
	}
	return 0
}

func (x *ToggleEquipRequest) GetEquipSlotId() uint64 {
	if x != nil {
		return x.EquipSlotId
	}
	return 0
}

func (x *ToggleEquipRequest) GetShouldEquip() bool {
	if x != nil {
		return x.ShouldEquip
	}
	return false
}

type ToggleEquipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleEquipResponse) Reset() {
	*x = ToggleEquipResponse{}
	mi := &file_char_char_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleEquipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleEquipResponse) ProtoMessage() {}

func (x *ToggleEquipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleEquipResponse.ProtoReflect.Descriptor instead.
func (*ToggleEquipResponse) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{15}
}

func (x *ToggleEquipResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToggleEquipResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EquipItemRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CharacterId    uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ItemInstanceId uint64                 `protobuf:"varint,2,opt,name=item_instance_id,json=itemInstanceId,proto3" json:"item_instance_id,omitempty"`
	EquipSlotId    uint64                 `protobuf:"varint,3,opt,name=equip_slot_id,json=equipSlotId,proto3" json:"equip_slot_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EquipItemRequest) Reset() {
	*x = EquipItemRequest{}
	mi := &file_char_char_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipItemRequest) ProtoMessage() {}

func (x *EquipItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipItemRequest.ProtoReflect.Descriptor instead.
func (*EquipItemRequest) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{16}
}

func (x *EquipItemRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *EquipItemRequest) GetItemInstanceId() uint64 {
	if x != nil {
		return x.ItemInstanceId
	}
	return 0
}

func (x *EquipItemRequest) GetEquipSlotId() uint64 {
	if x != nil {
		return x.EquipSlotId
	}
	return 0
}

type EquipItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipItemResponse) Reset() {
	*x = EquipItemResponse{}
	mi := &file_char_char_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipItemResponse) ProtoMessage() {}

func (x *EquipItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipItemResponse.ProtoReflect.Descriptor instead.
func (*EquipItemResponse) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{17}
}

func (x *EquipItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EquipItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnequipItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	EquipSlotId   uint64                 `protobuf:"varint,2,opt,name=equip_slot_id,json=equipSlotId,proto3" json:"equip_slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnequipItemRequest) Reset() {
	*x = UnequipItemRequest{}
	mi := &file_char_char_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnequipItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnequipItemRequest) ProtoMessage() {}

func (x *UnequipItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnequipItemRequest.ProtoReflect.Descriptor instead.
func (*UnequipItemRequest) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{18}
}

func (x *UnequipItemRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *UnequipItemRequest) GetEquipSlotId() uint64 {
	if x != nil {
		return x.EquipSlotId
	}
	return 0
}

type UnequipItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnequipItemResponse) Reset() {
	*x = UnequipItemResponse{}
	mi := &file_char_char_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnequipItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnequipItemResponse) ProtoMessage() {}

func (x *UnequipItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnequipItemResponse.ProtoReflect.Descriptor instead.
func (*UnequipItemResponse) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{19}
}

func (x *UnequipItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnequipItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetEquippedItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEquippedItemsRequest) Reset() {
	*x = GetEquippedItemsRequest{}
	mi := &file_char_char_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEquippedItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEquippedItemsRequest) ProtoMessage() {}

func (x *GetEquippedItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEquippedItemsRequest.ProtoReflect.Descriptor instead.
func (*GetEquippedItemsRequest) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{20}
}

func (x *GetEquippedItemsRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type GetEquippedItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemInstances []*repo.ItemInstance   `protobuf:"bytes,1,rep,name=itemInstances,proto3" json:"itemInstances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEquippedItemsResponse) Reset() {
	*x = GetEquippedItemsResponse{}
	mi := &file_char_char_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEquippedItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEquippedItemsResponse) ProtoMessage() {}

func (x *GetEquippedItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEquippedItemsResponse.ProtoReflect.Descriptor instead.
func (*GetEquippedItemsResponse) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{21}
}

func (x *GetEquippedItemsResponse) GetItemInstances() []*repo.ItemInstance {
	if x != nil {
		return x.ItemInstances
	}
	return nil
}

type GetEquipSlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEquipSlotsRequest) Reset() {
	*x = GetEquipSlotsRequest{}
	mi := &file_char_char_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEquipSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEquipSlotsRequest) ProtoMessage() {}

func (x *GetEquipSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEquipSlotsRequest.ProtoReflect.Descriptor instead.
func (*GetEquipSlotsRequest) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{22}
}

type GetEquipSlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*repo.EquipSlot      `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEquipSlotsResponse) Reset() {
	*x = GetEquipSlotsResponse{}
	mi := &file_char_char_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEquipSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEquipSlotsResponse) ProtoMessage() {}

func (x *GetEquipSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_char_char_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEquipSlotsResponse.ProtoReflect.Descriptor instead.
func (*GetEquipSlotsResponse) Descriptor() ([]byte, []int) {
	return file_char_char_proto_rawDescGZIP(), []int{23}
}

func (x *GetEquipSlotsResponse) GetSlots() []*repo.EquipSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

var File_char_char_proto protoreflect.FileDescriptor

const file_char_char_proto_rawDesc = "" +
	"\n" +
	"\x0fchar/char.proto\x12\x04char\x1a\x0frepo/repo.proto\x1a\x13health/health.proto\"\x13\n" +
	"\x11ListHeroesRequest\"8\n" +
	"\x12ListHeroesResponse\x12\"\n" +
	"\x06heroes\x18\x01 \x03(\v2\n" +
	".repo.HeroR\x06heroes\"3\n" +
	"\x15ListCharactersRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"I\n" +
	"\x16ListCharactersResponse\x12/\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x0f.repo.CharacterR\n" +
	"characters\"Y\n" +
	"\x1bSetSelectedCharacterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\x04R\vcharacterId\"R\n" +
	"\x1cSetSelectedCharacterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\x1fGetLastSelectedCharacterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"Q\n" +
	" GetLastSelectedCharacterResponse\x12-\n" +
	"\tcharacter\x18\x01 \x01(\v2\x0f.repo.CharacterR\tcharacter\"8\n" +
	"\x13GetCharacterRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\"E\n" +
	"\x14GetCharacterResponse\x12-\n" +
	"\tcharacter\x18\x01 \x01(\v2\x0f.repo.CharacterR\tcharacter\"e\n" +
	"\x16CreateCharacterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1e\n" +
	"\x04hero\x18\x02 \x01(\v2\n" +
	".repo.HeroR\x04hero\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"|\n" +
	"\x17CreateCharacterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\tcharacter\x18\x03 \x01(\v2\x0f.repo.CharacterR\tcharacter\";\n" +
	"\x16DeleteCharacterRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\"M\n" +
	"\x17DeleteCharacterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa7\x01\n" +
	"\x12ToggleEquipRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\x12(\n" +
	"\x10item_instance_id\x18\x02 \x01(\x04R\x0eitemInstanceId\x12\"\n" +
	"\requip_slot_id\x18\x03 \x01(\x04R\vequipSlotId\x12 \n" +
	"\vshouldEquip\x18\x04 \x01(\bR\vshouldEquip\"I\n" +
	"\x13ToggleEquipResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x83\x01\n" +
	"\x10EquipItemRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\x12(\n" +
	"\x10item_instance_id\x18\x02 \x01(\x04R\x0eitemInstanceId\x12\"\n" +
	"\requip_slot_id\x18\x03 \x01(\x04R\vequipSlotId\"G\n" +
	"\x11EquipItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"[\n" +
	"\x12UnequipItemRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\x12\"\n" +
	"\requip_slot_id\x18\x02 \x01(\x04R\vequipSlotId\"I\n" +
	"\x13UnequipItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"<\n" +
	"\x17GetEquippedItemsRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\"T\n" +
	"\x18GetEquippedItemsResponse\x128\n" +
	"\ritemInstances\x18\x01 \x03(\v2\x12.repo.ItemInstanceR\ritemInstances\"\x16\n" +
	"\x14GetEquipSlotsRequest\">\n" +
	"\x15GetEquipSlotsResponse\x12%\n" +
	"\x05slots\x18\x01 \x03(\v2\x0f.repo.EquipSlotR\x05slots2\xef\a\n" +
	"\tCharacter\x12@\n" +
	"\x05Check\x12\x1a.health.HealthCheckRequest\x1a\x1b.health.HealthCheckResponse\x12?\n" +
	"\n" +
	"ListHeroes\x12\x17.char.ListHeroesRequest\x1a\x18.char.ListHeroesResponse\x12K\n" +
	"\x0eListCharacters\x12\x1b.char.ListCharactersRequest\x1a\x1c.char.ListCharactersResponse\x12]\n" +
	"\x14SetSelectedCharacter\x12!.char.SetSelectedCharacterRequest\x1a\".char.SetSelectedCharacterResponse\x12i\n" +
	"\x18GetLastSelectedCharacter\x12%.char.GetLastSelectedCharacterRequest\x1a&.char.GetLastSelectedCharacterResponse\x12E\n" +
	"\fGetCharacter\x12\x19.char.GetCharacterRequest\x1a\x1a.char.GetCharacterResponse\x12N\n" +
	"\x0fCreateCharacter\x12\x1c.char.CreateCharacterRequest\x1a\x1d.char.CreateCharacterResponse\x12N\n" +
	"\x0fDeleteCharacter\x12\x1c.char.DeleteCharacterRequest\x1a\x1d.char.DeleteCharacterResponse\x12Q\n" +
	"\x10GetEquippedItems\x12\x1d.char.GetEquippedItemsRequest\x1a\x1e.char.GetEquippedItemsResponse\x12B\n" +
	"\vToggleEquip\x12\x18.char.ToggleEquipRequest\x1a\x19.char.ToggleEquipResponse\x12<\n" +
	"\tEquipItem\x12\x16.char.EquipItemRequest\x1a\x17.char.EquipItemResponse\x12B\n" +
	"\vUnequipItem\x12\x18.char.UnequipItemRequest\x1a\x19.char.UnequipItemResponse\x12H\n" +
	"\rGetEquipSlots\x12\x1a.char.GetEquipSlotsRequest\x1a\x1b.char.GetEquipSlotsResponseB6Z4github.com/komadiina/spelltext/proto/proto/char;charb\x06proto3"

var (
	file_char_char_proto_rawDescOnce sync.Once
	file_char_char_proto_rawDescData []byte
)

func file_char_char_proto_rawDescGZIP() []byte {
	file_char_char_proto_rawDescOnce.Do(func() {
		file_char_char_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_char_char_proto_rawDesc), len(file_char_char_proto_rawDesc)))
	})
	return file_char_char_proto_rawDescData
}

var file_char_char_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_char_char_proto_goTypes = []any{
	(*ListHeroesRequest)(nil),                // 0: char.ListHeroesRequest
	(*ListHeroesResponse)(nil),               // 1: char.ListHeroesResponse
	(*ListCharactersRequest)(nil),            // 2: char.ListCharactersRequest
	(*ListCharactersResponse)(nil),           // 3: char.ListCharactersResponse
	(*SetSelectedCharacterRequest)(nil),      // 4: char.SetSelectedCharacterRequest
	(*SetSelectedCharacterResponse)(nil),     // 5: char.SetSelectedCharacterResponse
	(*GetLastSelectedCharacterRequest)(nil),  // 6: char.GetLastSelectedCharacterRequest
	(*GetLastSelectedCharacterResponse)(nil), // 7: char.GetLastSelectedCharacterResponse
	(*GetCharacterRequest)(nil),              // 8: char.GetCharacterRequest
	(*GetCharacterResponse)(nil),             // 9: char.GetCharacterResponse
	(*CreateCharacterRequest)(nil),           // 10: char.CreateCharacterRequest
	(*CreateCharacterResponse)(nil),          // 11: char.CreateCharacterResponse
	(*DeleteCharacterRequest)(nil),           // 12: char.DeleteCharacterRequest
	(*DeleteCharacterResponse)(nil),          // 13: char.DeleteCharacterResponse
	(*ToggleEquipRequest)(nil),               // 14: char.ToggleEquipRequest
	(*ToggleEquipResponse)(nil),              // 15: char.ToggleEquipResponse
	(*EquipItemRequest)(nil),                 // 16: char.EquipItemRequest
	(*EquipItemResponse)(nil),                // 17: char.EquipItemResponse
	(*UnequipItemRequest)(nil),               // 18: char.UnequipItemRequest
	(*UnequipItemResponse)(nil),              // 19: char.UnequipItemResponse
	(*GetEquippedItemsRequest)(nil),          // 20: char.GetEquippedItemsRequest
	(*GetEquippedItemsResponse)(nil),         // 21: char.GetEquippedItemsResponse
	(*GetEquipSlotsRequest)(nil),             // 22: char.GetEquipSlotsRequest
	(*GetEquipSlotsResponse)(nil),            // 23: char.GetEquipSlotsResponse
	(*repo.Hero)(nil),                        // 24: repo.Hero
	(*repo.Character)(nil),                   // 25: repo.Character
	(*repo.ItemInstance)(nil),                // 26: repo.ItemInstance
	(*repo.EquipSlot)(nil),                   // 27: repo.EquipSlot
	(*health.HealthCheckRequest)(nil),        // 28: health.HealthCheckRequest
	(*health.HealthCheckResponse)(nil),       // 29: health.HealthCheckResponse
}
var file_char_char_proto_depIdxs = []int32{
	24, // 0: char.ListHeroesResponse.heroes:type_name -> repo.Hero
	25, // 1: char.ListCharactersResponse.characters:type_name -> repo.Character
	25, // 2: char.GetLastSelectedCharacterResponse.character:type_name -> repo.Character
	25, // 3: char.GetCharacterResponse.character:type_name -> repo.Character
	24, // 4: char.CreateCharacterRequest.hero:type_name -> repo.Hero
	25, // 5: char.CreateCharacterResponse.character:type_name -> repo.Character
	26, // 6: char.GetEquippedItemsResponse.itemInstances:type_name -> repo.ItemInstance
	27, // 7: char.GetEquipSlotsResponse.slots:type_name -> repo.EquipSlot
	28, // 8: char.Character.Check:input_type -> health.HealthCheckRequest
	0,  // 9: char.Character.ListHeroes:input_type -> char.ListHeroesRequest
	2,  // 10: char.Character.ListCharacters:input_type -> char.ListCharactersRequest
	4,  // 11: char.Character.SetSelectedCharacter:input_type -> char.SetSelectedCharacterRequest
	6,  // 12: char.Character.GetLastSelectedCharacter:input_type -> char.GetLastSelectedCharacterRequest
	8,  // 13: char.Character.GetCharacter:input_type -> char.GetCharacterRequest
	10, // 14: char.Character.CreateCharacter:input_type -> char.CreateCharacterRequest
	12, // 15: char.Character.DeleteCharacter:input_type -> char.DeleteCharacterRequest
	20, // 16: char.Character.GetEquippedItems:input_type -> char.GetEquippedItemsRequest
	14, // 17: char.Character.ToggleEquip:input_type -> char.ToggleEquipRequest
	16, // 18: char.Character.EquipItem:input_type -> char.EquipItemRequest
	18, // 19: char.Character.UnequipItem:input_type -> char.UnequipItemRequest
	22, // 20: char.Character.GetEquipSlots:input_type -> char.GetEquipSlotsRequest
	29, // 21: char.Character.Check:output_type -> health.HealthCheckResponse
	1,  // 22: char.Character.ListHeroes:output_type -> char.ListHeroesResponse
	3,  // 23: char.Character.ListCharacters:output_type -> char.ListCharactersResponse
	5,  // 24: char.Character.SetSelectedCharacter:output_type -> char.SetSelectedCharacterResponse
	7,  // 25: char.Character.GetLastSelectedCharacter:output_type -> char.GetLastSelectedCharacterResponse
	9,  // 26: char.Character.GetCharacter:output_type -> char.GetCharacterResponse
	11, // 27: char.Character.CreateCharacter:output_type -> char.CreateCharacterResponse
	13, // 28: char.Character.DeleteCharacter:output_type -> char.DeleteCharacterResponse
	21, // 29: char.Character.GetEquippedItems:output_type -> char.GetEquippedItemsResponse
	15, // 30: char.Character.ToggleEquip:output_type -> char.ToggleEquipResponse
	17, // 31: char.Character.EquipItem:output_type -> char.EquipItemResponse
	19, // 32: char.Character.UnequipItem:output_type -> char.UnequipItemResponse
	23, // 33: char.Character.GetEquipSlots:output_type -> char.GetEquipSlotsResponse
	21, // [21:34] is the sub-list for method output_type
	8,  // [8:21] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_char_char_proto_init() }
func file_char_char_proto_init() {
	if File_char_char_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_char_char_proto_rawDesc), len(file_char_char_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_char_char_proto_goTypes,
		DependencyIndexes: file_char_char_proto_depIdxs,
		MessageInfos:      file_char_char_proto_msgTypes,
	}.Build()
	File_char_char_proto = out.File
	file_char_char_proto_goTypes = nil
	file_char_char_proto_depIdxs = nil
}
