// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: armory/armory.proto

package armory

import (
	repo "github.com/komadiina/spelltext/proto/repo"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListHeroesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHeroesRequest) Reset() {
	*x = ListHeroesRequest{}
	mi := &file_armory_armory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHeroesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHeroesRequest) ProtoMessage() {}

func (x *ListHeroesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHeroesRequest.ProtoReflect.Descriptor instead.
func (*ListHeroesRequest) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{0}
}

type ListHeroesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Heroes        []*repo.Hero           `protobuf:"bytes,1,rep,name=heroes,proto3" json:"heroes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHeroesResponse) Reset() {
	*x = ListHeroesResponse{}
	mi := &file_armory_armory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHeroesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHeroesResponse) ProtoMessage() {}

func (x *ListHeroesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHeroesResponse.ProtoReflect.Descriptor instead.
func (*ListHeroesResponse) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{1}
}

func (x *ListHeroesResponse) GetHeroes() []*repo.Hero {
	if x != nil {
		return x.Heroes
	}
	return nil
}

type ListCharactersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharactersRequest) Reset() {
	*x = ListCharactersRequest{}
	mi := &file_armory_armory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharactersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharactersRequest) ProtoMessage() {}

func (x *ListCharactersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharactersRequest.ProtoReflect.Descriptor instead.
func (*ListCharactersRequest) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{2}
}

func (x *ListCharactersRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ListCharactersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*repo.Character      `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharactersResponse) Reset() {
	*x = ListCharactersResponse{}
	mi := &file_armory_armory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharactersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharactersResponse) ProtoMessage() {}

func (x *ListCharactersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharactersResponse.ProtoReflect.Descriptor instead.
func (*ListCharactersResponse) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{3}
}

func (x *ListCharactersResponse) GetCharacters() []*repo.Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

type SetSelectedCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CharacterId   uint64                 `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSelectedCharacterRequest) Reset() {
	*x = SetSelectedCharacterRequest{}
	mi := &file_armory_armory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSelectedCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSelectedCharacterRequest) ProtoMessage() {}

func (x *SetSelectedCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSelectedCharacterRequest.ProtoReflect.Descriptor instead.
func (*SetSelectedCharacterRequest) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{4}
}

func (x *SetSelectedCharacterRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetSelectedCharacterRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type SetSelectedCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSelectedCharacterResponse) Reset() {
	*x = SetSelectedCharacterResponse{}
	mi := &file_armory_armory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSelectedCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSelectedCharacterResponse) ProtoMessage() {}

func (x *SetSelectedCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSelectedCharacterResponse.ProtoReflect.Descriptor instead.
func (*SetSelectedCharacterResponse) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{5}
}

func (x *SetSelectedCharacterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetSelectedCharacterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLastSelectedCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastSelectedCharacterRequest) Reset() {
	*x = GetLastSelectedCharacterRequest{}
	mi := &file_armory_armory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastSelectedCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastSelectedCharacterRequest) ProtoMessage() {}

func (x *GetLastSelectedCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastSelectedCharacterRequest.ProtoReflect.Descriptor instead.
func (*GetLastSelectedCharacterRequest) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{6}
}

func (x *GetLastSelectedCharacterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetLastSelectedCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *repo.Character        `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastSelectedCharacterResponse) Reset() {
	*x = GetLastSelectedCharacterResponse{}
	mi := &file_armory_armory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastSelectedCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastSelectedCharacterResponse) ProtoMessage() {}

func (x *GetLastSelectedCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastSelectedCharacterResponse.ProtoReflect.Descriptor instead.
func (*GetLastSelectedCharacterResponse) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{7}
}

func (x *GetLastSelectedCharacterResponse) GetCharacter() *repo.Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type GetCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterRequest) Reset() {
	*x = GetCharacterRequest{}
	mi := &file_armory_armory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterRequest) ProtoMessage() {}

func (x *GetCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterRequest) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{8}
}

func (x *GetCharacterRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type GetCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *repo.Character        `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterResponse) Reset() {
	*x = GetCharacterResponse{}
	mi := &file_armory_armory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterResponse) ProtoMessage() {}

func (x *GetCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterResponse.ProtoReflect.Descriptor instead.
func (*GetCharacterResponse) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{9}
}

func (x *GetCharacterResponse) GetCharacter() *repo.Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type CreateCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Hero          *repo.Hero             `protobuf:"bytes,2,opt,name=hero,proto3" json:"hero,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterRequest) Reset() {
	*x = CreateCharacterRequest{}
	mi := &file_armory_armory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterRequest) ProtoMessage() {}

func (x *CreateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterRequest.ProtoReflect.Descriptor instead.
func (*CreateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCharacterRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCharacterRequest) GetHero() *repo.Hero {
	if x != nil {
		return x.Hero
	}
	return nil
}

func (x *CreateCharacterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Character     *repo.Character        `protobuf:"bytes,3,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterResponse) Reset() {
	*x = CreateCharacterResponse{}
	mi := &file_armory_armory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterResponse) ProtoMessage() {}

func (x *CreateCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterResponse.ProtoReflect.Descriptor instead.
func (*CreateCharacterResponse) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{11}
}

func (x *CreateCharacterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateCharacterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateCharacterResponse) GetCharacter() *repo.Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type DeleteCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterRequest) Reset() {
	*x = DeleteCharacterRequest{}
	mi := &file_armory_armory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterRequest) ProtoMessage() {}

func (x *DeleteCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterRequest.ProtoReflect.Descriptor instead.
func (*DeleteCharacterRequest) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCharacterRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type DeleteCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterResponse) Reset() {
	*x = DeleteCharacterResponse{}
	mi := &file_armory_armory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterResponse) ProtoMessage() {}

func (x *DeleteCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterResponse.ProtoReflect.Descriptor instead.
func (*DeleteCharacterResponse) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteCharacterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCharacterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EquipItemRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CharacterId    uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ItemInstanceId uint64                 `protobuf:"varint,2,opt,name=item_instance_id,json=itemInstanceId,proto3" json:"item_instance_id,omitempty"`
	EquipSlotId    uint64                 `protobuf:"varint,3,opt,name=equip_slot_id,json=equipSlotId,proto3" json:"equip_slot_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EquipItemRequest) Reset() {
	*x = EquipItemRequest{}
	mi := &file_armory_armory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipItemRequest) ProtoMessage() {}

func (x *EquipItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipItemRequest.ProtoReflect.Descriptor instead.
func (*EquipItemRequest) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{14}
}

func (x *EquipItemRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *EquipItemRequest) GetItemInstanceId() uint64 {
	if x != nil {
		return x.ItemInstanceId
	}
	return 0
}

func (x *EquipItemRequest) GetEquipSlotId() uint64 {
	if x != nil {
		return x.EquipSlotId
	}
	return 0
}

type EquipItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipItemResponse) Reset() {
	*x = EquipItemResponse{}
	mi := &file_armory_armory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipItemResponse) ProtoMessage() {}

func (x *EquipItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipItemResponse.ProtoReflect.Descriptor instead.
func (*EquipItemResponse) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{15}
}

func (x *EquipItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EquipItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnequipItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	EquipSlotId   uint64                 `protobuf:"varint,2,opt,name=equip_slot_id,json=equipSlotId,proto3" json:"equip_slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnequipItemRequest) Reset() {
	*x = UnequipItemRequest{}
	mi := &file_armory_armory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnequipItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnequipItemRequest) ProtoMessage() {}

func (x *UnequipItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnequipItemRequest.ProtoReflect.Descriptor instead.
func (*UnequipItemRequest) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{16}
}

func (x *UnequipItemRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *UnequipItemRequest) GetEquipSlotId() uint64 {
	if x != nil {
		return x.EquipSlotId
	}
	return 0
}

type UnequipItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnequipItemResponse) Reset() {
	*x = UnequipItemResponse{}
	mi := &file_armory_armory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnequipItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnequipItemResponse) ProtoMessage() {}

func (x *UnequipItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnequipItemResponse.ProtoReflect.Descriptor instead.
func (*UnequipItemResponse) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{17}
}

func (x *UnequipItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnequipItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetEquippedItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEquippedItemsRequest) Reset() {
	*x = GetEquippedItemsRequest{}
	mi := &file_armory_armory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEquippedItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEquippedItemsRequest) ProtoMessage() {}

func (x *GetEquippedItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEquippedItemsRequest.ProtoReflect.Descriptor instead.
func (*GetEquippedItemsRequest) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{18}
}

func (x *GetEquippedItemsRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type GetEquippedItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*repo.Item           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEquippedItemsResponse) Reset() {
	*x = GetEquippedItemsResponse{}
	mi := &file_armory_armory_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEquippedItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEquippedItemsResponse) ProtoMessage() {}

func (x *GetEquippedItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_armory_armory_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEquippedItemsResponse.ProtoReflect.Descriptor instead.
func (*GetEquippedItemsResponse) Descriptor() ([]byte, []int) {
	return file_armory_armory_proto_rawDescGZIP(), []int{19}
}

func (x *GetEquippedItemsResponse) GetItems() []*repo.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_armory_armory_proto protoreflect.FileDescriptor

const file_armory_armory_proto_rawDesc = "" +
	"\n" +
	"\x13armory/armory.proto\x12\x06armory\x1a\x0frepo/repo.proto\"\x13\n" +
	"\x11ListHeroesRequest\"8\n" +
	"\x12ListHeroesResponse\x12\"\n" +
	"\x06heroes\x18\x01 \x03(\v2\n" +
	".repo.HeroR\x06heroes\"3\n" +
	"\x15ListCharactersRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"I\n" +
	"\x16ListCharactersResponse\x12/\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x0f.repo.CharacterR\n" +
	"characters\"Y\n" +
	"\x1bSetSelectedCharacterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\x04R\vcharacterId\"R\n" +
	"\x1cSetSelectedCharacterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\x1fGetLastSelectedCharacterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"Q\n" +
	" GetLastSelectedCharacterResponse\x12-\n" +
	"\tcharacter\x18\x01 \x01(\v2\x0f.repo.CharacterR\tcharacter\"8\n" +
	"\x13GetCharacterRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\"E\n" +
	"\x14GetCharacterResponse\x12-\n" +
	"\tcharacter\x18\x01 \x01(\v2\x0f.repo.CharacterR\tcharacter\"e\n" +
	"\x16CreateCharacterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1e\n" +
	"\x04hero\x18\x02 \x01(\v2\n" +
	".repo.HeroR\x04hero\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"|\n" +
	"\x17CreateCharacterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\tcharacter\x18\x03 \x01(\v2\x0f.repo.CharacterR\tcharacter\";\n" +
	"\x16DeleteCharacterRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\"M\n" +
	"\x17DeleteCharacterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x83\x01\n" +
	"\x10EquipItemRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\x12(\n" +
	"\x10item_instance_id\x18\x02 \x01(\x04R\x0eitemInstanceId\x12\"\n" +
	"\requip_slot_id\x18\x03 \x01(\x04R\vequipSlotId\"G\n" +
	"\x11EquipItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"[\n" +
	"\x12UnequipItemRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\x12\"\n" +
	"\requip_slot_id\x18\x02 \x01(\x04R\vequipSlotId\"I\n" +
	"\x13UnequipItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"<\n" +
	"\x17GetEquippedItemsRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\"<\n" +
	"\x18GetEquippedItemsResponse\x12 \n" +
	"\x05items\x18\x01 \x03(\v2\n" +
	".repo.ItemR\x05items2\xc7\x06\n" +
	"\tCharacter\x12C\n" +
	"\n" +
	"ListHeroes\x12\x19.armory.ListHeroesRequest\x1a\x1a.armory.ListHeroesResponse\x12O\n" +
	"\x0eListCharacters\x12\x1d.armory.ListCharactersRequest\x1a\x1e.armory.ListCharactersResponse\x12a\n" +
	"\x14SetSelectedCharacter\x12#.armory.SetSelectedCharacterRequest\x1a$.armory.SetSelectedCharacterResponse\x12m\n" +
	"\x18GetLastSelectedCharacter\x12'.armory.GetLastSelectedCharacterRequest\x1a(.armory.GetLastSelectedCharacterResponse\x12I\n" +
	"\fGetCharacter\x12\x1b.armory.GetCharacterRequest\x1a\x1c.armory.GetCharacterResponse\x12R\n" +
	"\x0fCreateCharacter\x12\x1e.armory.CreateCharacterRequest\x1a\x1f.armory.CreateCharacterResponse\x12R\n" +
	"\x0fDeleteCharacter\x12\x1e.armory.DeleteCharacterRequest\x1a\x1f.armory.DeleteCharacterResponse\x12U\n" +
	"\x10GetEquippedItems\x12\x1f.armory.GetEquippedItemsRequest\x1a .armory.GetEquippedItemsResponse\x12@\n" +
	"\tEquipItem\x12\x18.armory.EquipItemRequest\x1a\x19.armory.EquipItemResponse\x12F\n" +
	"\vUnequipItem\x12\x1a.armory.UnequipItemRequest\x1a\x1b.armory.UnequipItemResponseB:Z8github.com/komadiina/spelltext/proto/proto/armory;armoryb\x06proto3"

var (
	file_armory_armory_proto_rawDescOnce sync.Once
	file_armory_armory_proto_rawDescData []byte
)

func file_armory_armory_proto_rawDescGZIP() []byte {
	file_armory_armory_proto_rawDescOnce.Do(func() {
		file_armory_armory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_armory_armory_proto_rawDesc), len(file_armory_armory_proto_rawDesc)))
	})
	return file_armory_armory_proto_rawDescData
}

var file_armory_armory_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_armory_armory_proto_goTypes = []any{
	(*ListHeroesRequest)(nil),                // 0: armory.ListHeroesRequest
	(*ListHeroesResponse)(nil),               // 1: armory.ListHeroesResponse
	(*ListCharactersRequest)(nil),            // 2: armory.ListCharactersRequest
	(*ListCharactersResponse)(nil),           // 3: armory.ListCharactersResponse
	(*SetSelectedCharacterRequest)(nil),      // 4: armory.SetSelectedCharacterRequest
	(*SetSelectedCharacterResponse)(nil),     // 5: armory.SetSelectedCharacterResponse
	(*GetLastSelectedCharacterRequest)(nil),  // 6: armory.GetLastSelectedCharacterRequest
	(*GetLastSelectedCharacterResponse)(nil), // 7: armory.GetLastSelectedCharacterResponse
	(*GetCharacterRequest)(nil),              // 8: armory.GetCharacterRequest
	(*GetCharacterResponse)(nil),             // 9: armory.GetCharacterResponse
	(*CreateCharacterRequest)(nil),           // 10: armory.CreateCharacterRequest
	(*CreateCharacterResponse)(nil),          // 11: armory.CreateCharacterResponse
	(*DeleteCharacterRequest)(nil),           // 12: armory.DeleteCharacterRequest
	(*DeleteCharacterResponse)(nil),          // 13: armory.DeleteCharacterResponse
	(*EquipItemRequest)(nil),                 // 14: armory.EquipItemRequest
	(*EquipItemResponse)(nil),                // 15: armory.EquipItemResponse
	(*UnequipItemRequest)(nil),               // 16: armory.UnequipItemRequest
	(*UnequipItemResponse)(nil),              // 17: armory.UnequipItemResponse
	(*GetEquippedItemsRequest)(nil),          // 18: armory.GetEquippedItemsRequest
	(*GetEquippedItemsResponse)(nil),         // 19: armory.GetEquippedItemsResponse
	(*repo.Hero)(nil),                        // 20: repo.Hero
	(*repo.Character)(nil),                   // 21: repo.Character
	(*repo.Item)(nil),                        // 22: repo.Item
}
var file_armory_armory_proto_depIdxs = []int32{
	20, // 0: armory.ListHeroesResponse.heroes:type_name -> repo.Hero
	21, // 1: armory.ListCharactersResponse.characters:type_name -> repo.Character
	21, // 2: armory.GetLastSelectedCharacterResponse.character:type_name -> repo.Character
	21, // 3: armory.GetCharacterResponse.character:type_name -> repo.Character
	20, // 4: armory.CreateCharacterRequest.hero:type_name -> repo.Hero
	21, // 5: armory.CreateCharacterResponse.character:type_name -> repo.Character
	22, // 6: armory.GetEquippedItemsResponse.items:type_name -> repo.Item
	0,  // 7: armory.Character.ListHeroes:input_type -> armory.ListHeroesRequest
	2,  // 8: armory.Character.ListCharacters:input_type -> armory.ListCharactersRequest
	4,  // 9: armory.Character.SetSelectedCharacter:input_type -> armory.SetSelectedCharacterRequest
	6,  // 10: armory.Character.GetLastSelectedCharacter:input_type -> armory.GetLastSelectedCharacterRequest
	8,  // 11: armory.Character.GetCharacter:input_type -> armory.GetCharacterRequest
	10, // 12: armory.Character.CreateCharacter:input_type -> armory.CreateCharacterRequest
	12, // 13: armory.Character.DeleteCharacter:input_type -> armory.DeleteCharacterRequest
	18, // 14: armory.Character.GetEquippedItems:input_type -> armory.GetEquippedItemsRequest
	14, // 15: armory.Character.EquipItem:input_type -> armory.EquipItemRequest
	16, // 16: armory.Character.UnequipItem:input_type -> armory.UnequipItemRequest
	1,  // 17: armory.Character.ListHeroes:output_type -> armory.ListHeroesResponse
	3,  // 18: armory.Character.ListCharacters:output_type -> armory.ListCharactersResponse
	5,  // 19: armory.Character.SetSelectedCharacter:output_type -> armory.SetSelectedCharacterResponse
	7,  // 20: armory.Character.GetLastSelectedCharacter:output_type -> armory.GetLastSelectedCharacterResponse
	9,  // 21: armory.Character.GetCharacter:output_type -> armory.GetCharacterResponse
	11, // 22: armory.Character.CreateCharacter:output_type -> armory.CreateCharacterResponse
	13, // 23: armory.Character.DeleteCharacter:output_type -> armory.DeleteCharacterResponse
	19, // 24: armory.Character.GetEquippedItems:output_type -> armory.GetEquippedItemsResponse
	15, // 25: armory.Character.EquipItem:output_type -> armory.EquipItemResponse
	17, // 26: armory.Character.UnequipItem:output_type -> armory.UnequipItemResponse
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_armory_armory_proto_init() }
func file_armory_armory_proto_init() {
	if File_armory_armory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_armory_armory_proto_rawDesc), len(file_armory_armory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_armory_armory_proto_goTypes,
		DependencyIndexes: file_armory_armory_proto_depIdxs,
		MessageInfos:      file_armory_armory_proto_msgTypes,
	}.Build()
	File_armory_armory_proto = out.File
	file_armory_armory_proto_goTypes = nil
	file_armory_armory_proto_depIdxs = nil
}
