// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: armory.proto

package armory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TCharacter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Class         string                 `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	Level         uint32                 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Gold          uint64                 `protobuf:"varint,5,opt,name=gold,proto3" json:"gold,omitempty"`
	Tokens        uint64                 `protobuf:"varint,6,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCharacter) Reset() {
	*x = TCharacter{}
	mi := &file_armory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCharacter) ProtoMessage() {}

func (x *TCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_armory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCharacter.ProtoReflect.Descriptor instead.
func (*TCharacter) Descriptor() ([]byte, []int) {
	return file_armory_proto_rawDescGZIP(), []int{0}
}

func (x *TCharacter) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TCharacter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TCharacter) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *TCharacter) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *TCharacter) GetGold() uint64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *TCharacter) GetTokens() uint64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

type THero struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *THero) Reset() {
	*x = THero{}
	mi := &file_armory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *THero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*THero) ProtoMessage() {}

func (x *THero) ProtoReflect() protoreflect.Message {
	mi := &file_armory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use THero.ProtoReflect.Descriptor instead.
func (*THero) Descriptor() ([]byte, []int) {
	return file_armory_proto_rawDescGZIP(), []int{1}
}

func (x *THero) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *THero) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListHeroesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHeroesRequest) Reset() {
	*x = ListHeroesRequest{}
	mi := &file_armory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHeroesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHeroesRequest) ProtoMessage() {}

func (x *ListHeroesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_armory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHeroesRequest.ProtoReflect.Descriptor instead.
func (*ListHeroesRequest) Descriptor() ([]byte, []int) {
	return file_armory_proto_rawDescGZIP(), []int{2}
}

type ListHeroesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Heroes        []*THero               `protobuf:"bytes,1,rep,name=heroes,proto3" json:"heroes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHeroesResponse) Reset() {
	*x = ListHeroesResponse{}
	mi := &file_armory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHeroesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHeroesResponse) ProtoMessage() {}

func (x *ListHeroesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_armory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHeroesResponse.ProtoReflect.Descriptor instead.
func (*ListHeroesResponse) Descriptor() ([]byte, []int) {
	return file_armory_proto_rawDescGZIP(), []int{3}
}

func (x *ListHeroesResponse) GetHeroes() []*THero {
	if x != nil {
		return x.Heroes
	}
	return nil
}

type ListCharactersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharactersRequest) Reset() {
	*x = ListCharactersRequest{}
	mi := &file_armory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharactersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharactersRequest) ProtoMessage() {}

func (x *ListCharactersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_armory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharactersRequest.ProtoReflect.Descriptor instead.
func (*ListCharactersRequest) Descriptor() ([]byte, []int) {
	return file_armory_proto_rawDescGZIP(), []int{4}
}

func (x *ListCharactersRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ListCharactersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*TCharacter          `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharactersResponse) Reset() {
	*x = ListCharactersResponse{}
	mi := &file_armory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharactersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharactersResponse) ProtoMessage() {}

func (x *ListCharactersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_armory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharactersResponse.ProtoReflect.Descriptor instead.
func (*ListCharactersResponse) Descriptor() ([]byte, []int) {
	return file_armory_proto_rawDescGZIP(), []int{5}
}

func (x *ListCharactersResponse) GetCharacters() []*TCharacter {
	if x != nil {
		return x.Characters
	}
	return nil
}

type CreateCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hero          *THero                 `protobuf:"bytes,1,opt,name=hero,proto3" json:"hero,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterRequest) Reset() {
	*x = CreateCharacterRequest{}
	mi := &file_armory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterRequest) ProtoMessage() {}

func (x *CreateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_armory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterRequest.ProtoReflect.Descriptor instead.
func (*CreateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_armory_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCharacterRequest) GetHero() *THero {
	if x != nil {
		return x.Hero
	}
	return nil
}

func (x *CreateCharacterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterResponse) Reset() {
	*x = CreateCharacterResponse{}
	mi := &file_armory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterResponse) ProtoMessage() {}

func (x *CreateCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_armory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterResponse.ProtoReflect.Descriptor instead.
func (*CreateCharacterResponse) Descriptor() ([]byte, []int) {
	return file_armory_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCharacterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateCharacterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterRequest) Reset() {
	*x = DeleteCharacterRequest{}
	mi := &file_armory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterRequest) ProtoMessage() {}

func (x *DeleteCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_armory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterRequest.ProtoReflect.Descriptor instead.
func (*DeleteCharacterRequest) Descriptor() ([]byte, []int) {
	return file_armory_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCharacterRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type DeleteCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterResponse) Reset() {
	*x = DeleteCharacterResponse{}
	mi := &file_armory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterResponse) ProtoMessage() {}

func (x *DeleteCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_armory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterResponse.ProtoReflect.Descriptor instead.
func (*DeleteCharacterResponse) Descriptor() ([]byte, []int) {
	return file_armory_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCharacterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCharacterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_armory_proto protoreflect.FileDescriptor

const file_armory_proto_rawDesc = "" +
	"\n" +
	"\farmory.proto\x12\x06armory\"\x88\x01\n" +
	"\n" +
	"TCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x14\n" +
	"\x05level\x18\x04 \x01(\rR\x05level\x12\x12\n" +
	"\x04gold\x18\x05 \x01(\x04R\x04gold\x12\x16\n" +
	"\x06tokens\x18\x06 \x01(\x04R\x06tokens\"+\n" +
	"\x05THero\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\"\x13\n" +
	"\x11ListHeroesRequest\";\n" +
	"\x12ListHeroesResponse\x12%\n" +
	"\x06heroes\x18\x01 \x03(\v2\r.armory.THeroR\x06heroes\"3\n" +
	"\x15ListCharactersRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"L\n" +
	"\x16ListCharactersResponse\x122\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x12.armory.TCharacterR\n" +
	"characters\"O\n" +
	"\x16CreateCharacterRequest\x12!\n" +
	"\x04hero\x18\x01 \x01(\v2\r.armory.THeroR\x04hero\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"M\n" +
	"\x17CreateCharacterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\";\n" +
	"\x16DeleteCharacterRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\"M\n" +
	"\x17DeleteCharacterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc9\x02\n" +
	"\tCharacter\x12C\n" +
	"\n" +
	"ListHeroes\x12\x19.armory.ListHeroesRequest\x1a\x1a.armory.ListHeroesResponse\x12O\n" +
	"\x0eListCharacters\x12\x1d.armory.ListCharactersRequest\x1a\x1e.armory.ListCharactersResponse\x12R\n" +
	"\x0fCreateCharacter\x12\x1e.armory.CreateCharacterRequest\x1a\x1f.armory.CreateCharacterResponse\x12R\n" +
	"\x0fDeleteCharacter\x12\x1e.armory.DeleteCharacterRequest\x1a\x1f.armory.DeleteCharacterResponseB\x15Z\x13proto/armory;armoryb\x06proto3"

var (
	file_armory_proto_rawDescOnce sync.Once
	file_armory_proto_rawDescData []byte
)

func file_armory_proto_rawDescGZIP() []byte {
	file_armory_proto_rawDescOnce.Do(func() {
		file_armory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_armory_proto_rawDesc), len(file_armory_proto_rawDesc)))
	})
	return file_armory_proto_rawDescData
}

var file_armory_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_armory_proto_goTypes = []any{
	(*TCharacter)(nil),              // 0: armory.TCharacter
	(*THero)(nil),                   // 1: armory.THero
	(*ListHeroesRequest)(nil),       // 2: armory.ListHeroesRequest
	(*ListHeroesResponse)(nil),      // 3: armory.ListHeroesResponse
	(*ListCharactersRequest)(nil),   // 4: armory.ListCharactersRequest
	(*ListCharactersResponse)(nil),  // 5: armory.ListCharactersResponse
	(*CreateCharacterRequest)(nil),  // 6: armory.CreateCharacterRequest
	(*CreateCharacterResponse)(nil), // 7: armory.CreateCharacterResponse
	(*DeleteCharacterRequest)(nil),  // 8: armory.DeleteCharacterRequest
	(*DeleteCharacterResponse)(nil), // 9: armory.DeleteCharacterResponse
}
var file_armory_proto_depIdxs = []int32{
	1, // 0: armory.ListHeroesResponse.heroes:type_name -> armory.THero
	0, // 1: armory.ListCharactersResponse.characters:type_name -> armory.TCharacter
	1, // 2: armory.CreateCharacterRequest.hero:type_name -> armory.THero
	2, // 3: armory.Character.ListHeroes:input_type -> armory.ListHeroesRequest
	4, // 4: armory.Character.ListCharacters:input_type -> armory.ListCharactersRequest
	6, // 5: armory.Character.CreateCharacter:input_type -> armory.CreateCharacterRequest
	8, // 6: armory.Character.DeleteCharacter:input_type -> armory.DeleteCharacterRequest
	3, // 7: armory.Character.ListHeroes:output_type -> armory.ListHeroesResponse
	5, // 8: armory.Character.ListCharacters:output_type -> armory.ListCharactersResponse
	7, // 9: armory.Character.CreateCharacter:output_type -> armory.CreateCharacterResponse
	9, // 10: armory.Character.DeleteCharacter:output_type -> armory.DeleteCharacterResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_armory_proto_init() }
func file_armory_proto_init() {
	if File_armory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_armory_proto_rawDesc), len(file_armory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_armory_proto_goTypes,
		DependencyIndexes: file_armory_proto_depIdxs,
		MessageInfos:      file_armory_proto_msgTypes,
	}.Build()
	File_armory_proto = out.File
	file_armory_proto_goTypes = nil
	file_armory_proto_depIdxs = nil
}
