// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: gamba/gamba.proto

package gamba

import (
	health "github.com/komadiina/spelltext/proto/health"
	repo "github.com/komadiina/spelltext/proto/repo"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChestsRequest) Reset() {
	*x = GetChestsRequest{}
	mi := &file_gamba_gamba_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChestsRequest) ProtoMessage() {}

func (x *GetChestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamba_gamba_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChestsRequest.ProtoReflect.Descriptor instead.
func (*GetChestsRequest) Descriptor() ([]byte, []int) {
	return file_gamba_gamba_proto_rawDescGZIP(), []int{0}
}

type GetChestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chests        []*repo.GambaChest     `protobuf:"bytes,1,rep,name=chests,proto3" json:"chests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChestsResponse) Reset() {
	*x = GetChestsResponse{}
	mi := &file_gamba_gamba_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChestsResponse) ProtoMessage() {}

func (x *GetChestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamba_gamba_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChestsResponse.ProtoReflect.Descriptor instead.
func (*GetChestsResponse) Descriptor() ([]byte, []int) {
	return file_gamba_gamba_proto_rawDescGZIP(), []int{1}
}

func (x *GetChestsResponse) GetChests() []*repo.GambaChest {
	if x != nil {
		return x.Chests
	}
	return nil
}

type GetChestDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChestId       uint64                 `protobuf:"varint,1,opt,name=chest_id,json=chestId,proto3" json:"chest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChestDetailsRequest) Reset() {
	*x = GetChestDetailsRequest{}
	mi := &file_gamba_gamba_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChestDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChestDetailsRequest) ProtoMessage() {}

func (x *GetChestDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamba_gamba_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChestDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetChestDetailsRequest) Descriptor() ([]byte, []int) {
	return file_gamba_gamba_proto_rawDescGZIP(), []int{2}
}

func (x *GetChestDetailsRequest) GetChestId() uint64 {
	if x != nil {
		return x.ChestId
	}
	return 0
}

type GetChestDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*repo.Item           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChestDetailsResponse) Reset() {
	*x = GetChestDetailsResponse{}
	mi := &file_gamba_gamba_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChestDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChestDetailsResponse) ProtoMessage() {}

func (x *GetChestDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamba_gamba_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChestDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetChestDetailsResponse) Descriptor() ([]byte, []int) {
	return file_gamba_gamba_proto_rawDescGZIP(), []int{3}
}

func (x *GetChestDetailsResponse) GetItems() []*repo.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type OpenChestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ChestId       uint64                 `protobuf:"varint,2,opt,name=chest_id,json=chestId,proto3" json:"chest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenChestRequest) Reset() {
	*x = OpenChestRequest{}
	mi := &file_gamba_gamba_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenChestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenChestRequest) ProtoMessage() {}

func (x *OpenChestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamba_gamba_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenChestRequest.ProtoReflect.Descriptor instead.
func (*OpenChestRequest) Descriptor() ([]byte, []int) {
	return file_gamba_gamba_proto_rawDescGZIP(), []int{4}
}

func (x *OpenChestRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *OpenChestRequest) GetChestId() uint64 {
	if x != nil {
		return x.ChestId
	}
	return 0
}

type OpenChestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *repo.Item             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenChestResponse) Reset() {
	*x = OpenChestResponse{}
	mi := &file_gamba_gamba_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenChestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenChestResponse) ProtoMessage() {}

func (x *OpenChestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamba_gamba_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenChestResponse.ProtoReflect.Descriptor instead.
func (*OpenChestResponse) Descriptor() ([]byte, []int) {
	return file_gamba_gamba_proto_rawDescGZIP(), []int{5}
}

func (x *OpenChestResponse) GetItem() *repo.Item {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_gamba_gamba_proto protoreflect.FileDescriptor

const file_gamba_gamba_proto_rawDesc = "" +
	"\n" +
	"\x11gamba/gamba.proto\x12\x05gamba\x1a\x0frepo/repo.proto\x1a\x13health/health.proto\"\x12\n" +
	"\x10GetChestsRequest\"=\n" +
	"\x11GetChestsResponse\x12(\n" +
	"\x06chests\x18\x01 \x03(\v2\x10.repo.GambaChestR\x06chests\"3\n" +
	"\x16GetChestDetailsRequest\x12\x19\n" +
	"\bchest_id\x18\x01 \x01(\x04R\achestId\";\n" +
	"\x17GetChestDetailsResponse\x12 \n" +
	"\x05items\x18\x01 \x03(\v2\n" +
	".repo.ItemR\x05items\"P\n" +
	"\x10OpenChestRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\x12\x19\n" +
	"\bchest_id\x18\x02 \x01(\x04R\achestId\"3\n" +
	"\x11OpenChestResponse\x12\x1e\n" +
	"\x04item\x18\x01 \x01(\v2\n" +
	".repo.ItemR\x04item2\x9b\x02\n" +
	"\x05Gamba\x12@\n" +
	"\x05Check\x12\x1a.health.HealthCheckRequest\x1a\x1b.health.HealthCheckResponse\x12>\n" +
	"\tGetChests\x12\x17.gamba.GetChestsRequest\x1a\x18.gamba.GetChestsResponse\x12P\n" +
	"\x0fGetChestDetails\x12\x1d.gamba.GetChestDetailsRequest\x1a\x1e.gamba.GetChestDetailsResponse\x12>\n" +
	"\tOpenChest\x12\x17.gamba.OpenChestRequest\x1a\x18.gamba.OpenChestResponseB2Z0github.com/komadiina/spelltext/proto/gamba;gambab\x06proto3"

var (
	file_gamba_gamba_proto_rawDescOnce sync.Once
	file_gamba_gamba_proto_rawDescData []byte
)

func file_gamba_gamba_proto_rawDescGZIP() []byte {
	file_gamba_gamba_proto_rawDescOnce.Do(func() {
		file_gamba_gamba_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamba_gamba_proto_rawDesc), len(file_gamba_gamba_proto_rawDesc)))
	})
	return file_gamba_gamba_proto_rawDescData
}

var file_gamba_gamba_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gamba_gamba_proto_goTypes = []any{
	(*GetChestsRequest)(nil),           // 0: gamba.GetChestsRequest
	(*GetChestsResponse)(nil),          // 1: gamba.GetChestsResponse
	(*GetChestDetailsRequest)(nil),     // 2: gamba.GetChestDetailsRequest
	(*GetChestDetailsResponse)(nil),    // 3: gamba.GetChestDetailsResponse
	(*OpenChestRequest)(nil),           // 4: gamba.OpenChestRequest
	(*OpenChestResponse)(nil),          // 5: gamba.OpenChestResponse
	(*repo.GambaChest)(nil),            // 6: repo.GambaChest
	(*repo.Item)(nil),                  // 7: repo.Item
	(*health.HealthCheckRequest)(nil),  // 8: health.HealthCheckRequest
	(*health.HealthCheckResponse)(nil), // 9: health.HealthCheckResponse
}
var file_gamba_gamba_proto_depIdxs = []int32{
	6, // 0: gamba.GetChestsResponse.chests:type_name -> repo.GambaChest
	7, // 1: gamba.GetChestDetailsResponse.items:type_name -> repo.Item
	7, // 2: gamba.OpenChestResponse.item:type_name -> repo.Item
	8, // 3: gamba.Gamba.Check:input_type -> health.HealthCheckRequest
	0, // 4: gamba.Gamba.GetChests:input_type -> gamba.GetChestsRequest
	2, // 5: gamba.Gamba.GetChestDetails:input_type -> gamba.GetChestDetailsRequest
	4, // 6: gamba.Gamba.OpenChest:input_type -> gamba.OpenChestRequest
	9, // 7: gamba.Gamba.Check:output_type -> health.HealthCheckResponse
	1, // 8: gamba.Gamba.GetChests:output_type -> gamba.GetChestsResponse
	3, // 9: gamba.Gamba.GetChestDetails:output_type -> gamba.GetChestDetailsResponse
	5, // 10: gamba.Gamba.OpenChest:output_type -> gamba.OpenChestResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gamba_gamba_proto_init() }
func file_gamba_gamba_proto_init() {
	if File_gamba_gamba_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamba_gamba_proto_rawDesc), len(file_gamba_gamba_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gamba_gamba_proto_goTypes,
		DependencyIndexes: file_gamba_gamba_proto_depIdxs,
		MessageInfos:      file_gamba_gamba_proto_msgTypes,
	}.Build()
	File_gamba_gamba_proto = out.File
	file_gamba_gamba_proto_goTypes = nil
	file_gamba_gamba_proto_depIdxs = nil
}
