// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: combat/combat.proto

package combat

import (
	context "context"
	health "github.com/komadiina/spelltext/proto/health"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Combat_Check_FullMethodName      = "/combat.Combat/Check"
	Combat_ListNpcs_FullMethodName   = "/combat.Combat/ListNpcs"
	Combat_SubmitLoss_FullMethodName = "/combat.Combat/SubmitLoss"
	Combat_SubmitWin_FullMethodName  = "/combat.Combat/SubmitWin"
)

// CombatClient is the client API for Combat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CombatClient interface {
	Check(ctx context.Context, in *health.HealthCheckRequest, opts ...grpc.CallOption) (*health.HealthCheckResponse, error)
	ListNpcs(ctx context.Context, in *ListNpcsRequest, opts ...grpc.CallOption) (*ListNpcsResponse, error)
	SubmitLoss(ctx context.Context, in *SubmitLossRequest, opts ...grpc.CallOption) (*SubmitLossResponse, error)
	SubmitWin(ctx context.Context, in *SubmitWinRequest, opts ...grpc.CallOption) (*SubmitWinResponse, error)
}

type combatClient struct {
	cc grpc.ClientConnInterface
}

func NewCombatClient(cc grpc.ClientConnInterface) CombatClient {
	return &combatClient{cc}
}

func (c *combatClient) Check(ctx context.Context, in *health.HealthCheckRequest, opts ...grpc.CallOption) (*health.HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(health.HealthCheckResponse)
	err := c.cc.Invoke(ctx, Combat_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *combatClient) ListNpcs(ctx context.Context, in *ListNpcsRequest, opts ...grpc.CallOption) (*ListNpcsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNpcsResponse)
	err := c.cc.Invoke(ctx, Combat_ListNpcs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *combatClient) SubmitLoss(ctx context.Context, in *SubmitLossRequest, opts ...grpc.CallOption) (*SubmitLossResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitLossResponse)
	err := c.cc.Invoke(ctx, Combat_SubmitLoss_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *combatClient) SubmitWin(ctx context.Context, in *SubmitWinRequest, opts ...grpc.CallOption) (*SubmitWinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitWinResponse)
	err := c.cc.Invoke(ctx, Combat_SubmitWin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CombatServer is the server API for Combat service.
// All implementations must embed UnimplementedCombatServer
// for forward compatibility.
type CombatServer interface {
	Check(context.Context, *health.HealthCheckRequest) (*health.HealthCheckResponse, error)
	ListNpcs(context.Context, *ListNpcsRequest) (*ListNpcsResponse, error)
	SubmitLoss(context.Context, *SubmitLossRequest) (*SubmitLossResponse, error)
	SubmitWin(context.Context, *SubmitWinRequest) (*SubmitWinResponse, error)
	mustEmbedUnimplementedCombatServer()
}

// UnimplementedCombatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCombatServer struct{}

func (UnimplementedCombatServer) Check(context.Context, *health.HealthCheckRequest) (*health.HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedCombatServer) ListNpcs(context.Context, *ListNpcsRequest) (*ListNpcsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNpcs not implemented")
}
func (UnimplementedCombatServer) SubmitLoss(context.Context, *SubmitLossRequest) (*SubmitLossResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitLoss not implemented")
}
func (UnimplementedCombatServer) SubmitWin(context.Context, *SubmitWinRequest) (*SubmitWinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitWin not implemented")
}
func (UnimplementedCombatServer) mustEmbedUnimplementedCombatServer() {}
func (UnimplementedCombatServer) testEmbeddedByValue()                {}

// UnsafeCombatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CombatServer will
// result in compilation errors.
type UnsafeCombatServer interface {
	mustEmbedUnimplementedCombatServer()
}

func RegisterCombatServer(s grpc.ServiceRegistrar, srv CombatServer) {
	// If the following call pancis, it indicates UnimplementedCombatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Combat_ServiceDesc, srv)
}

func _Combat_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(health.HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Combat_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatServer).Check(ctx, req.(*health.HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Combat_ListNpcs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNpcsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatServer).ListNpcs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Combat_ListNpcs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatServer).ListNpcs(ctx, req.(*ListNpcsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Combat_SubmitLoss_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitLossRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatServer).SubmitLoss(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Combat_SubmitLoss_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatServer).SubmitLoss(ctx, req.(*SubmitLossRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Combat_SubmitWin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitWinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatServer).SubmitWin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Combat_SubmitWin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatServer).SubmitWin(ctx, req.(*SubmitWinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Combat_ServiceDesc is the grpc.ServiceDesc for Combat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Combat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "combat.Combat",
	HandlerType: (*CombatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Combat_Check_Handler,
		},
		{
			MethodName: "ListNpcs",
			Handler:    _Combat_ListNpcs_Handler,
		},
		{
			MethodName: "SubmitLoss",
			Handler:    _Combat_SubmitLoss_Handler,
		},
		{
			MethodName: "SubmitWin",
			Handler:    _Combat_SubmitWin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "combat/combat.proto",
}
