// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: combat/combat.proto

package combat

import (
	repo "github.com/komadiina/spelltext/proto/repo"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitiateCombatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	NpcIds        []uint64               `protobuf:"varint,2,rep,packed,name=npc_ids,json=npcIds,proto3" json:"npc_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateCombatRequest) Reset() {
	*x = InitiateCombatRequest{}
	mi := &file_combat_combat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateCombatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateCombatRequest) ProtoMessage() {}

func (x *InitiateCombatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_combat_combat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateCombatRequest.ProtoReflect.Descriptor instead.
func (*InitiateCombatRequest) Descriptor() ([]byte, []int) {
	return file_combat_combat_proto_rawDescGZIP(), []int{0}
}

func (x *InitiateCombatRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *InitiateCombatRequest) GetNpcIds() []uint64 {
	if x != nil {
		return x.NpcIds
	}
	return nil
}

type InitiateCombatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Npcs          []*repo.Npc            `protobuf:"bytes,1,rep,name=npcs,proto3" json:"npcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateCombatResponse) Reset() {
	*x = InitiateCombatResponse{}
	mi := &file_combat_combat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateCombatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateCombatResponse) ProtoMessage() {}

func (x *InitiateCombatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_combat_combat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateCombatResponse.ProtoReflect.Descriptor instead.
func (*InitiateCombatResponse) Descriptor() ([]byte, []int) {
	return file_combat_combat_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateCombatResponse) GetNpcs() []*repo.Npc {
	if x != nil {
		return x.Npcs
	}
	return nil
}

type ResolveCombatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	NpcIds        []uint64               `protobuf:"varint,2,rep,packed,name=npc_ids,json=npcIds,proto3" json:"npc_ids,omitempty"`
	Wins          []bool                 `protobuf:"varint,3,rep,packed,name=wins,proto3" json:"wins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCombatRequest) Reset() {
	*x = ResolveCombatRequest{}
	mi := &file_combat_combat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCombatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCombatRequest) ProtoMessage() {}

func (x *ResolveCombatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_combat_combat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCombatRequest.ProtoReflect.Descriptor instead.
func (*ResolveCombatRequest) Descriptor() ([]byte, []int) {
	return file_combat_combat_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveCombatRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *ResolveCombatRequest) GetNpcIds() []uint64 {
	if x != nil {
		return x.NpcIds
	}
	return nil
}

func (x *ResolveCombatRequest) GetWins() []bool {
	if x != nil {
		return x.Wins
	}
	return nil
}

type ResolveCombatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XpGained      uint64                 `protobuf:"varint,1,opt,name=xp_gained,json=xpGained,proto3" json:"xp_gained,omitempty"`
	GoldGained    uint64                 `protobuf:"varint,2,opt,name=gold_gained,json=goldGained,proto3" json:"gold_gained,omitempty"`
	TokensGained  uint64                 `protobuf:"varint,3,opt,name=tokens_gained,json=tokensGained,proto3" json:"tokens_gained,omitempty"`
	ItemsGained   []*repo.Item           `protobuf:"bytes,4,rep,name=items_gained,json=itemsGained,proto3" json:"items_gained,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCombatResponse) Reset() {
	*x = ResolveCombatResponse{}
	mi := &file_combat_combat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCombatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCombatResponse) ProtoMessage() {}

func (x *ResolveCombatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_combat_combat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCombatResponse.ProtoReflect.Descriptor instead.
func (*ResolveCombatResponse) Descriptor() ([]byte, []int) {
	return file_combat_combat_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveCombatResponse) GetXpGained() uint64 {
	if x != nil {
		return x.XpGained
	}
	return 0
}

func (x *ResolveCombatResponse) GetGoldGained() uint64 {
	if x != nil {
		return x.GoldGained
	}
	return 0
}

func (x *ResolveCombatResponse) GetTokensGained() uint64 {
	if x != nil {
		return x.TokensGained
	}
	return 0
}

func (x *ResolveCombatResponse) GetItemsGained() []*repo.Item {
	if x != nil {
		return x.ItemsGained
	}
	return nil
}

type ListNpcsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// lists npc's whose min_level < character.level < max_level
	CharacterId   uint64 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNpcsRequest) Reset() {
	*x = ListNpcsRequest{}
	mi := &file_combat_combat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNpcsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNpcsRequest) ProtoMessage() {}

func (x *ListNpcsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_combat_combat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNpcsRequest.ProtoReflect.Descriptor instead.
func (*ListNpcsRequest) Descriptor() ([]byte, []int) {
	return file_combat_combat_proto_rawDescGZIP(), []int{4}
}

func (x *ListNpcsRequest) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type ListNpcsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Npcs          []*repo.Npc            `protobuf:"bytes,1,rep,name=npcs,proto3" json:"npcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNpcsResponse) Reset() {
	*x = ListNpcsResponse{}
	mi := &file_combat_combat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNpcsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNpcsResponse) ProtoMessage() {}

func (x *ListNpcsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_combat_combat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNpcsResponse.ProtoReflect.Descriptor instead.
func (*ListNpcsResponse) Descriptor() ([]byte, []int) {
	return file_combat_combat_proto_rawDescGZIP(), []int{5}
}

func (x *ListNpcsResponse) GetNpcs() []*repo.Npc {
	if x != nil {
		return x.Npcs
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_combat_combat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_combat_combat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_combat_combat_proto_rawDescGZIP(), []int{6}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_combat_combat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_combat_combat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_combat_combat_proto_rawDescGZIP(), []int{7}
}

var File_combat_combat_proto protoreflect.FileDescriptor

const file_combat_combat_proto_rawDesc = "" +
	"\n" +
	"\x13combat/combat.proto\x12\x06combat\x1a\x0frepo/repo.proto\"S\n" +
	"\x15InitiateCombatRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\x12\x17\n" +
	"\anpc_ids\x18\x02 \x03(\x04R\x06npcIds\"7\n" +
	"\x16InitiateCombatResponse\x12\x1d\n" +
	"\x04npcs\x18\x01 \x03(\v2\t.repo.NpcR\x04npcs\"f\n" +
	"\x14ResolveCombatRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\x12\x17\n" +
	"\anpc_ids\x18\x02 \x03(\x04R\x06npcIds\x12\x12\n" +
	"\x04wins\x18\x03 \x03(\bR\x04wins\"\xa9\x01\n" +
	"\x15ResolveCombatResponse\x12\x1b\n" +
	"\txp_gained\x18\x01 \x01(\x04R\bxpGained\x12\x1f\n" +
	"\vgold_gained\x18\x02 \x01(\x04R\n" +
	"goldGained\x12#\n" +
	"\rtokens_gained\x18\x03 \x01(\x04R\ftokensGained\x12-\n" +
	"\fitems_gained\x18\x04 \x03(\v2\n" +
	".repo.ItemR\vitemsGained\"4\n" +
	"\x0fListNpcsRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\"1\n" +
	"\x10ListNpcsResponse\x12\x1d\n" +
	"\x04npcs\x18\x01 \x03(\v2\t.repo.NpcR\x04npcs\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse2\x99\x02\n" +
	"\x06Combat\x121\n" +
	"\x04Ping\x12\x13.combat.PingRequest\x1a\x14.combat.PingResponse\x12=\n" +
	"\bListNpcs\x12\x17.combat.ListNpcsRequest\x1a\x18.combat.ListNpcsResponse\x12O\n" +
	"\x0eInitiateCombat\x12\x1d.combat.InitiateCombatRequest\x1a\x1e.combat.InitiateCombatResponse\x12L\n" +
	"\rResolveCombat\x12\x1c.combat.ResolveCombatRequest\x1a\x1d.combat.ResolveCombatResponseB4Z2github.com/komadiina/spelltext/proto/combat;combatb\x06proto3"

var (
	file_combat_combat_proto_rawDescOnce sync.Once
	file_combat_combat_proto_rawDescData []byte
)

func file_combat_combat_proto_rawDescGZIP() []byte {
	file_combat_combat_proto_rawDescOnce.Do(func() {
		file_combat_combat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_combat_combat_proto_rawDesc), len(file_combat_combat_proto_rawDesc)))
	})
	return file_combat_combat_proto_rawDescData
}

var file_combat_combat_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_combat_combat_proto_goTypes = []any{
	(*InitiateCombatRequest)(nil),  // 0: combat.InitiateCombatRequest
	(*InitiateCombatResponse)(nil), // 1: combat.InitiateCombatResponse
	(*ResolveCombatRequest)(nil),   // 2: combat.ResolveCombatRequest
	(*ResolveCombatResponse)(nil),  // 3: combat.ResolveCombatResponse
	(*ListNpcsRequest)(nil),        // 4: combat.ListNpcsRequest
	(*ListNpcsResponse)(nil),       // 5: combat.ListNpcsResponse
	(*PingRequest)(nil),            // 6: combat.PingRequest
	(*PingResponse)(nil),           // 7: combat.PingResponse
	(*repo.Npc)(nil),               // 8: repo.Npc
	(*repo.Item)(nil),              // 9: repo.Item
}
var file_combat_combat_proto_depIdxs = []int32{
	8, // 0: combat.InitiateCombatResponse.npcs:type_name -> repo.Npc
	9, // 1: combat.ResolveCombatResponse.items_gained:type_name -> repo.Item
	8, // 2: combat.ListNpcsResponse.npcs:type_name -> repo.Npc
	6, // 3: combat.Combat.Ping:input_type -> combat.PingRequest
	4, // 4: combat.Combat.ListNpcs:input_type -> combat.ListNpcsRequest
	0, // 5: combat.Combat.InitiateCombat:input_type -> combat.InitiateCombatRequest
	2, // 6: combat.Combat.ResolveCombat:input_type -> combat.ResolveCombatRequest
	7, // 7: combat.Combat.Ping:output_type -> combat.PingResponse
	5, // 8: combat.Combat.ListNpcs:output_type -> combat.ListNpcsResponse
	1, // 9: combat.Combat.InitiateCombat:output_type -> combat.InitiateCombatResponse
	3, // 10: combat.Combat.ResolveCombat:output_type -> combat.ResolveCombatResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_combat_combat_proto_init() }
func file_combat_combat_proto_init() {
	if File_combat_combat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_combat_combat_proto_rawDesc), len(file_combat_combat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_combat_combat_proto_goTypes,
		DependencyIndexes: file_combat_combat_proto_depIdxs,
		MessageInfos:      file_combat_combat_proto_msgTypes,
	}.Build()
	File_combat_combat_proto = out.File
	file_combat_combat_proto_goTypes = nil
	file_combat_combat_proto_depIdxs = nil
}
