namespace:
  name: spelltext
  environment: dev

# core services
nats:
  enabled: true
  config:
    replicaCount: 3
    jetstream:
      enabled: true
      fileStore: 
        dir: /data/jetstream
        maxSize: 10Gi
    auth:
      enabled: false
    persistence:
      enabled: true

flyway:
  enabled: true
  image: "ghcr.io/komadiina/spelltext/flyway:0.2.0"
  database:
    url: "jdbc:postgresql://spelltext-postgresql-ha-pgpool:5432/spelltext"
    user: postgres
    password: changeme
  
primary:
  extraVolumeMounts:
    - name: flyway-scripts
      mountPath: /flyway/sql
  
extraVolumes:
  - name: flyway-scripts
    persistentVolumeClaim:
      claimName: flyway-scripts-pvc

  
# spelltext service
chatserver:
  enabled: true
  image: "ghcr.io/komadiina/spelltext/chatserver:0.2.0"
  port: 50051
  portName: "grpc"
  containerPort: 50051
  targetPort: 50051
  protocol: "TCP"